//! Byte-exact A32 encoding tests for arm32 `Emit`.
//!
//! GENERATED by ci/arm32_encoding_oracle.py from ci/arm32_encoding_oracle.s;
//! do not edit. The expected bytes are what `zig cc -target
//! arm-linux-musleabihf` assembles each entry to. Regenerate with
//! `python3 ci/arm32_encoding_oracle.py`; CI runs it with `--check`.

const std = @import("std");
const emit = @import("Emit.zig");
const E = emit.Emit(.arm32musl);
const ModImm = emit.ModImm;
const GeneralReg = E.GeneralReg;

test "arm32 encoding: mov r0, r1" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.movRegReg(.r0, .r1);
    // e1a00001
    try std.testing.expectEqualSlices(u8, &.{ 0x01, 0x00, 0xa0, 0xe1 }, e.buf.items);
}

test "arm32 encoding: mov r11, sp" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.movRegReg(.r11, .r13);
    // e1a0b00d
    try std.testing.expectEqualSlices(u8, &.{ 0x0d, 0xb0, 0xa0, 0xe1 }, e.buf.items);
}

test "arm32 encoding: movne r3, r12" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.movRegRegCond(.ne, .r3, .r12);
    // 11a0300c
    try std.testing.expectEqualSlices(u8, &.{ 0x0c, 0x30, 0xa0, 0x11 }, e.buf.items);
}

test "arm32 encoding: mov r2, #255" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.movRegModImm(.r2, ModImm.of(255));
    // e3a020ff
    try std.testing.expectEqualSlices(u8, &.{ 0xff, 0x20, 0xa0, 0xe3 }, e.buf.items);
}

test "arm32 encoding: mov r2, #0xff000000" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.movRegModImm(.r2, ModImm.of(0xff000000));
    // e3a024ff
    try std.testing.expectEqualSlices(u8, &.{ 0xff, 0x24, 0xa0, 0xe3 }, e.buf.items);
}

test "arm32 encoding: mov r9, #0x3fc" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.movRegModImm(.r9, ModImm.of(0x3fc));
    // e3a09fff
    try std.testing.expectEqualSlices(u8, &.{ 0xff, 0x9f, 0xa0, 0xe3 }, e.buf.items);
}

test "arm32 encoding: moveq r0, #1" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.movRegModImmCond(.eq, .r0, ModImm.of(1));
    // 03a00001
    try std.testing.expectEqualSlices(u8, &.{ 0x01, 0x00, 0xa0, 0x03 }, e.buf.items);
}

test "arm32 encoding: movlt r10, #0" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.movRegModImmCond(.lt, .r10, ModImm.of(0));
    // b3a0a000
    try std.testing.expectEqualSlices(u8, &.{ 0x00, 0xa0, 0xa0, 0xb3 }, e.buf.items);
}

test "arm32 encoding: mvn r5, #0" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.mvnRegModImm(.r5, ModImm.of(0));
    // e3e05000
    try std.testing.expectEqualSlices(u8, &.{ 0x00, 0x50, 0xe0, 0xe3 }, e.buf.items);
}

test "arm32 encoding: mvn r5, r6" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.mvnRegReg(.r5, .r6);
    // e1e05006
    try std.testing.expectEqualSlices(u8, &.{ 0x06, 0x50, 0xe0, 0xe1 }, e.buf.items);
}

test "arm32 encoding: movw r7, #0x1234" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.movw(.r7, 0x1234);
    // e3017234
    try std.testing.expectEqualSlices(u8, &.{ 0x34, 0x72, 0x01, 0xe3 }, e.buf.items);
}

test "arm32 encoding: movw r12, #0xffff" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.movw(.r12, 0xffff);
    // e30fcfff
    try std.testing.expectEqualSlices(u8, &.{ 0xff, 0xcf, 0x0f, 0xe3 }, e.buf.items);
}

test "arm32 encoding: movt r7, #0xabcd" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.movt(.r7, 0xabcd);
    // e34a7bcd
    try std.testing.expectEqualSlices(u8, &.{ 0xcd, 0x7b, 0x4a, 0xe3 }, e.buf.items);
}

test "arm32 encoding: mov r0, #1024" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.movRegImm32(.r0, 0x400);
    // e3a00b01
    try std.testing.expectEqualSlices(u8, &.{ 0x01, 0x0b, 0xa0, 0xe3 }, e.buf.items);
}

test "arm32 encoding: mvn r1, #255" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.movRegImm32(.r1, 0xffffff00);
    // e3e010ff
    try std.testing.expectEqualSlices(u8, &.{ 0xff, 0x10, 0xe0, 0xe3 }, e.buf.items);
}

test "arm32 encoding: movw r2, #0xabcd" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.movRegImm32(.r2, 0xabcd);
    // e30a2bcd
    try std.testing.expectEqualSlices(u8, &.{ 0xcd, 0x2b, 0x0a, 0xe3 }, e.buf.items);
}

test "arm32 encoding: movw r3, #0x5678; movt r3, #0x1234" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.movRegImm32(.r3, 0x12345678);
    // e3053678 e3413234
    try std.testing.expectEqualSlices(u8, &.{ 0x78, 0x36, 0x05, 0xe3, 0x34, 0x32, 0x41, 0xe3 }, e.buf.items);
}

test "arm32 encoding: movw r4, #0; movt r4, #0x1235" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.movRegImm32(.r4, 0x12350000);
    // e3004000 e3414235
    try std.testing.expectEqualSlices(u8, &.{ 0x00, 0x40, 0x00, 0xe3, 0x35, 0x42, 0x41, 0xe3 }, e.buf.items);
}

test "arm32 encoding: add r0, r1, r2" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.addRegRegReg(.r0, .r1, .r2);
    // e0810002
    try std.testing.expectEqualSlices(u8, &.{ 0x02, 0x00, 0x81, 0xe0 }, e.buf.items);
}

test "arm32 encoding: adds r3, r4, r5" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.addsRegRegReg(.r3, .r4, .r5);
    // e0943005
    try std.testing.expectEqualSlices(u8, &.{ 0x05, 0x30, 0x94, 0xe0 }, e.buf.items);
}

test "arm32 encoding: adc r6, r7, r8" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.adcRegRegReg(.r6, .r7, .r8);
    // e0a76008
    try std.testing.expectEqualSlices(u8, &.{ 0x08, 0x60, 0xa7, 0xe0 }, e.buf.items);
}

test "arm32 encoding: adcs r9, r10, r11" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.adcsRegRegReg(.r9, .r10, .r11);
    // e0ba900b
    try std.testing.expectEqualSlices(u8, &.{ 0x0b, 0x90, 0xba, 0xe0 }, e.buf.items);
}

test "arm32 encoding: sub r0, r1, r2" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.subRegRegReg(.r0, .r1, .r2);
    // e0410002
    try std.testing.expectEqualSlices(u8, &.{ 0x02, 0x00, 0x41, 0xe0 }, e.buf.items);
}

test "arm32 encoding: subs r12, r0, r1" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.subsRegRegReg(.r12, .r0, .r1);
    // e050c001
    try std.testing.expectEqualSlices(u8, &.{ 0x01, 0xc0, 0x50, 0xe0 }, e.buf.items);
}

test "arm32 encoding: sbc r2, r3, r4" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.sbcRegRegReg(.r2, .r3, .r4);
    // e0c32004
    try std.testing.expectEqualSlices(u8, &.{ 0x04, 0x20, 0xc3, 0xe0 }, e.buf.items);
}

test "arm32 encoding: sbcs r5, r6, r7" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.sbcsRegRegReg(.r5, .r6, .r7);
    // e0d65007
    try std.testing.expectEqualSlices(u8, &.{ 0x07, 0x50, 0xd6, 0xe0 }, e.buf.items);
}

test "arm32 encoding: add r0, r11, #4080" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.addRegRegModImm(.r0, .r11, ModImm.of(4080));
    // e28b0eff
    try std.testing.expectEqualSlices(u8, &.{ 0xff, 0x0e, 0x8b, 0xe2 }, e.buf.items);
}

test "arm32 encoding: add r12, sp, #8" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.addRegRegModImm(.r12, .r13, ModImm.of(8));
    // e28dc008
    try std.testing.expectEqualSlices(u8, &.{ 0x08, 0xc0, 0x8d, 0xe2 }, e.buf.items);
}

test "arm32 encoding: adds r1, r1, #1" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.addsRegRegModImm(.r1, .r1, ModImm.of(1));
    // e2911001
    try std.testing.expectEqualSlices(u8, &.{ 0x01, 0x10, 0x91, 0xe2 }, e.buf.items);
}

test "arm32 encoding: sub sp, sp, #256" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.subRegRegModImm(.r13, .r13, ModImm.of(256));
    // e24ddc01
    try std.testing.expectEqualSlices(u8, &.{ 0x01, 0xdc, 0x4d, 0xe2 }, e.buf.items);
}

test "arm32 encoding: sub r12, r11, #0x10000" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.subRegRegModImm(.r12, .r11, ModImm.of(0x10000));
    // e24bc801
    try std.testing.expectEqualSlices(u8, &.{ 0x01, 0xc8, 0x4b, 0xe2 }, e.buf.items);
}

test "arm32 encoding: subs r3, r2, #32" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.subsRegRegModImm(.r3, .r2, ModImm.of(32));
    // e2523020
    try std.testing.expectEqualSlices(u8, &.{ 0x20, 0x30, 0x52, 0xe2 }, e.buf.items);
}

test "arm32 encoding: rsb r0, r1, #0" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.rsbRegRegModImm(.r0, .r1, ModImm.of(0));
    // e2610000
    try std.testing.expectEqualSlices(u8, &.{ 0x00, 0x00, 0x61, 0xe2 }, e.buf.items);
}

test "arm32 encoding: rsb r12, r2, #32" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.rsbRegRegModImm(.r12, .r2, ModImm.of(32));
    // e262c020
    try std.testing.expectEqualSlices(u8, &.{ 0x20, 0xc0, 0x62, 0xe2 }, e.buf.items);
}

test "arm32 encoding: rsbs r0, r0, #0" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.rsbsRegRegModImm(.r0, .r0, ModImm.of(0));
    // e2700000
    try std.testing.expectEqualSlices(u8, &.{ 0x00, 0x00, 0x70, 0xe2 }, e.buf.items);
}

test "arm32 encoding: rsc r1, r1, #0" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.rscRegRegModImm(.r1, .r1, ModImm.of(0));
    // e2e11000
    try std.testing.expectEqualSlices(u8, &.{ 0x00, 0x10, 0xe1, 0xe2 }, e.buf.items);
}

test "arm32 encoding: and r0, r1, r2" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.andRegRegReg(.r0, .r1, .r2);
    // e0010002
    try std.testing.expectEqualSlices(u8, &.{ 0x02, 0x00, 0x01, 0xe0 }, e.buf.items);
}

test "arm32 encoding: orr r3, r4, r5" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.orrRegRegReg(.r3, .r4, .r5);
    // e1843005
    try std.testing.expectEqualSlices(u8, &.{ 0x05, 0x30, 0x84, 0xe1 }, e.buf.items);
}

test "arm32 encoding: eor r6, r7, r8" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.eorRegRegReg(.r6, .r7, .r8);
    // e0276008
    try std.testing.expectEqualSlices(u8, &.{ 0x08, 0x60, 0x27, 0xe0 }, e.buf.items);
}

test "arm32 encoding: bic r9, r10, r12" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.bicRegRegReg(.r9, .r10, .r12);
    // e1ca900c
    try std.testing.expectEqualSlices(u8, &.{ 0x0c, 0x90, 0xca, 0xe1 }, e.buf.items);
}

test "arm32 encoding: and r0, r1, #255" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.andRegRegModImm(.r0, .r1, ModImm.of(255));
    // e20100ff
    try std.testing.expectEqualSlices(u8, &.{ 0xff, 0x00, 0x01, 0xe2 }, e.buf.items);
}

test "arm32 encoding: orr r0, r0, #0x80000000" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.orrRegRegModImm(.r0, .r0, ModImm.of(0x80000000));
    // e3800102
    try std.testing.expectEqualSlices(u8, &.{ 0x02, 0x01, 0x80, 0xe3 }, e.buf.items);
}

test "arm32 encoding: eor r2, r2, #1" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.eorRegRegModImm(.r2, .r2, ModImm.of(1));
    // e2222001
    try std.testing.expectEqualSlices(u8, &.{ 0x01, 0x20, 0x22, 0xe2 }, e.buf.items);
}

test "arm32 encoding: bic r3, r3, #0xff00" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.bicRegRegModImm(.r3, .r3, ModImm.of(0xff00));
    // e3c33cff
    try std.testing.expectEqualSlices(u8, &.{ 0xff, 0x3c, 0xc3, 0xe3 }, e.buf.items);
}

test "arm32 encoding: cmp r0, r1" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.cmpRegReg(.r0, .r1);
    // e1500001
    try std.testing.expectEqualSlices(u8, &.{ 0x01, 0x00, 0x50, 0xe1 }, e.buf.items);
}

test "arm32 encoding: cmp r10, r12" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.cmpRegReg(.r10, .r12);
    // e15a000c
    try std.testing.expectEqualSlices(u8, &.{ 0x0c, 0x00, 0x5a, 0xe1 }, e.buf.items);
}

test "arm32 encoding: cmp r0, #0" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.cmpRegModImm(.r0, ModImm.of(0));
    // e3500000
    try std.testing.expectEqualSlices(u8, &.{ 0x00, 0x00, 0x50, 0xe3 }, e.buf.items);
}

test "arm32 encoding: cmp r7, #0xff0" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.cmpRegModImm(.r7, ModImm.of(0xff0));
    // e3570eff
    try std.testing.expectEqualSlices(u8, &.{ 0xff, 0x0e, 0x57, 0xe3 }, e.buf.items);
}

test "arm32 encoding: cmn r0, #1" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.cmnRegModImm(.r0, ModImm.of(1));
    // e3700001
    try std.testing.expectEqualSlices(u8, &.{ 0x01, 0x00, 0x70, 0xe3 }, e.buf.items);
}

test "arm32 encoding: tst r0, r1" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.tstRegReg(.r0, .r1);
    // e1100001
    try std.testing.expectEqualSlices(u8, &.{ 0x01, 0x00, 0x10, 0xe1 }, e.buf.items);
}

test "arm32 encoding: tst r2, #1" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.tstRegModImm(.r2, ModImm.of(1));
    // e3120001
    try std.testing.expectEqualSlices(u8, &.{ 0x01, 0x00, 0x12, 0xe3 }, e.buf.items);
}

test "arm32 encoding: teq r3, r4" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.teqRegReg(.r3, .r4);
    // e1330004
    try std.testing.expectEqualSlices(u8, &.{ 0x04, 0x00, 0x33, 0xe1 }, e.buf.items);
}

test "arm32 encoding: orr r1, r1, r0, lsr r12" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.dataProc(.al, .orr, false, .r1, .r1, .{ .shift_reg = .{ .rm = .r0, .kind = .lsr, .rs = .r12 } });
    // e1811c30
    try std.testing.expectEqualSlices(u8, &.{ 0x30, 0x1c, 0x81, 0xe1 }, e.buf.items);
}

test "arm32 encoding: subgt r0, r1, r2, lsl #3" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.dataProc(.gt, .sub, false, .r0, .r1, .{ .shift_imm = .{ .rm = .r2, .kind = .lsl, .amount = 3 } });
    // c0410182
    try std.testing.expectEqualSlices(u8, &.{ 0x82, 0x01, 0x41, 0xc0 }, e.buf.items);
}

test "arm32 encoding: addsne r4, r5, r6, asr #32" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.dataProc(.ne, .add, true, .r4, .r5, .{ .shift_imm = .{ .rm = .r6, .kind = .asr, .amount = 32 } });
    // 10954046
    try std.testing.expectEqualSlices(u8, &.{ 0x46, 0x40, 0x95, 0x10 }, e.buf.items);
}

test "arm32 encoding: lslpl r1, r0, r3" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.dataProc(.pl, .mov, false, .r1, .r0, .{ .shift_reg = .{ .rm = .r0, .kind = .lsl, .rs = .r3 } });
    // 51a01310
    try std.testing.expectEqualSlices(u8, &.{ 0x10, 0x13, 0xa0, 0x51 }, e.buf.items);
}

test "arm32 encoding: cmp r1, r3, ror #7" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.dataProc(.al, .cmp, true, .r0, .r1, .{ .shift_imm = .{ .rm = .r3, .kind = .ror, .amount = 7 } });
    // e15103e3
    try std.testing.expectEqualSlices(u8, &.{ 0xe3, 0x03, 0x51, 0xe1 }, e.buf.items);
}

test "arm32 encoding: bichi r2, r2, #3" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.dataProc(.hi, .bic, false, .r2, .r2, .{ .imm = ModImm.of(3) });
    // 83c22003
    try std.testing.expectEqualSlices(u8, &.{ 0x03, 0x20, 0xc2, 0x83 }, e.buf.items);
}

test "arm32 encoding: lsl r0, r1, #31" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.lslRegRegImm(.r0, .r1, 31);
    // e1a00f81
    try std.testing.expectEqualSlices(u8, &.{ 0x81, 0x0f, 0xa0, 0xe1 }, e.buf.items);
}

test "arm32 encoding: lsl r8, r9, #1" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.lslRegRegImm(.r8, .r9, 1);
    // e1a08089
    try std.testing.expectEqualSlices(u8, &.{ 0x89, 0x80, 0xa0, 0xe1 }, e.buf.items);
}

test "arm32 encoding: lsr r0, r1, #32" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.lsrRegRegImm(.r0, .r1, 32);
    // e1a00021
    try std.testing.expectEqualSlices(u8, &.{ 0x21, 0x00, 0xa0, 0xe1 }, e.buf.items);
}

test "arm32 encoding: lsr r2, r3, #16" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.lsrRegRegImm(.r2, .r3, 16);
    // e1a02823
    try std.testing.expectEqualSlices(u8, &.{ 0x23, 0x28, 0xa0, 0xe1 }, e.buf.items);
}

test "arm32 encoding: asr r0, r1, #1" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.asrRegRegImm(.r0, .r1, 1);
    // e1a000c1
    try std.testing.expectEqualSlices(u8, &.{ 0xc1, 0x00, 0xa0, 0xe1 }, e.buf.items);
}

test "arm32 encoding: asr r4, r5, #32" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.asrRegRegImm(.r4, .r5, 32);
    // e1a04045
    try std.testing.expectEqualSlices(u8, &.{ 0x45, 0x40, 0xa0, 0xe1 }, e.buf.items);
}

test "arm32 encoding: ror r0, r1, #8" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.rorRegRegImm(.r0, .r1, 8);
    // e1a00461
    try std.testing.expectEqualSlices(u8, &.{ 0x61, 0x04, 0xa0, 0xe1 }, e.buf.items);
}

test "arm32 encoding: lsl r0, r1, r2" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.lslRegRegReg(.r0, .r1, .r2);
    // e1a00211
    try std.testing.expectEqualSlices(u8, &.{ 0x11, 0x02, 0xa0, 0xe1 }, e.buf.items);
}

test "arm32 encoding: lsr r3, r4, r12" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.lsrRegRegReg(.r3, .r4, .r12);
    // e1a03c34
    try std.testing.expectEqualSlices(u8, &.{ 0x34, 0x3c, 0xa0, 0xe1 }, e.buf.items);
}

test "arm32 encoding: asr r5, r6, r7" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.asrRegRegReg(.r5, .r6, .r7);
    // e1a05756
    try std.testing.expectEqualSlices(u8, &.{ 0x56, 0x57, 0xa0, 0xe1 }, e.buf.items);
}

test "arm32 encoding: ror r8, r9, r10" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.rorRegRegReg(.r8, .r9, .r10);
    // e1a08a79
    try std.testing.expectEqualSlices(u8, &.{ 0x79, 0x8a, 0xa0, 0xe1 }, e.buf.items);
}

test "arm32 encoding: mul r0, r1, r2" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.mulRegRegReg(.r0, .r1, .r2);
    // e0000291
    try std.testing.expectEqualSlices(u8, &.{ 0x91, 0x02, 0x00, 0xe0 }, e.buf.items);
}

test "arm32 encoding: mul r10, r9, r8" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.mulRegRegReg(.r10, .r9, .r8);
    // e00a0899
    try std.testing.expectEqualSlices(u8, &.{ 0x99, 0x08, 0x0a, 0xe0 }, e.buf.items);
}

test "arm32 encoding: mla r0, r1, r2, r3" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.mlaRegRegRegReg(.r0, .r1, .r2, .r3);
    // e0203291
    try std.testing.expectEqualSlices(u8, &.{ 0x91, 0x32, 0x20, 0xe0 }, e.buf.items);
}

test "arm32 encoding: mls r4, r5, r6, r7" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.mlsRegRegRegReg(.r4, .r5, .r6, .r7);
    // e0647695
    try std.testing.expectEqualSlices(u8, &.{ 0x95, 0x76, 0x64, 0xe0 }, e.buf.items);
}

test "arm32 encoding: umull r0, r1, r2, r3" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.umull(.r0, .r1, .r2, .r3);
    // e0810392
    try std.testing.expectEqualSlices(u8, &.{ 0x92, 0x03, 0x81, 0xe0 }, e.buf.items);
}

test "arm32 encoding: umlal r4, r5, r6, r7" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.umlal(.r4, .r5, .r6, .r7);
    // e0a54796
    try std.testing.expectEqualSlices(u8, &.{ 0x96, 0x47, 0xa5, 0xe0 }, e.buf.items);
}

test "arm32 encoding: smull r8, r9, r10, r12" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.smull(.r8, .r9, .r10, .r12);
    // e0c98c9a
    try std.testing.expectEqualSlices(u8, &.{ 0x9a, 0x8c, 0xc9, 0xe0 }, e.buf.items);
}

test "arm32 encoding: smlal r0, r12, r2, r3" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.smlal(.r0, .r12, .r2, .r3);
    // e0ec0392
    try std.testing.expectEqualSlices(u8, &.{ 0x92, 0x03, 0xec, 0xe0 }, e.buf.items);
}

test "arm32 encoding: clz r0, r1" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.clzRegReg(.r0, .r1);
    // e16f0f11
    try std.testing.expectEqualSlices(u8, &.{ 0x11, 0x0f, 0x6f, 0xe1 }, e.buf.items);
}

test "arm32 encoding: clz r12, r10" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.clzRegReg(.r12, .r10);
    // e16fcf1a
    try std.testing.expectEqualSlices(u8, &.{ 0x1a, 0xcf, 0x6f, 0xe1 }, e.buf.items);
}

test "arm32 encoding: rbit r2, r3" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.rbitRegReg(.r2, .r3);
    // e6ff2f33
    try std.testing.expectEqualSlices(u8, &.{ 0x33, 0x2f, 0xff, 0xe6 }, e.buf.items);
}

test "arm32 encoding: rev r4, r5" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.revRegReg(.r4, .r5);
    // e6bf4f35
    try std.testing.expectEqualSlices(u8, &.{ 0x35, 0x4f, 0xbf, 0xe6 }, e.buf.items);
}

test "arm32 encoding: rev16 r6, r7" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.rev16RegReg(.r6, .r7);
    // e6bf6fb7
    try std.testing.expectEqualSlices(u8, &.{ 0xb7, 0x6f, 0xbf, 0xe6 }, e.buf.items);
}

test "arm32 encoding: uxtb r0, r1" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.uxtbRegReg(.r0, .r1);
    // e6ef0071
    try std.testing.expectEqualSlices(u8, &.{ 0x71, 0x00, 0xef, 0xe6 }, e.buf.items);
}

test "arm32 encoding: uxth r2, r3" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.uxthRegReg(.r2, .r3);
    // e6ff2073
    try std.testing.expectEqualSlices(u8, &.{ 0x73, 0x20, 0xff, 0xe6 }, e.buf.items);
}

test "arm32 encoding: sxtb r4, r5" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.sxtbRegReg(.r4, .r5);
    // e6af4075
    try std.testing.expectEqualSlices(u8, &.{ 0x75, 0x40, 0xaf, 0xe6 }, e.buf.items);
}

test "arm32 encoding: sxth r10, r12" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.sxthRegReg(.r10, .r12);
    // e6bfa07c
    try std.testing.expectEqualSlices(u8, &.{ 0x7c, 0xa0, 0xbf, 0xe6 }, e.buf.items);
}

test "arm32 encoding: ubfx r0, r1, #3, #5" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.ubfx(.r0, .r1, 3, 5);
    // e7e401d1
    try std.testing.expectEqualSlices(u8, &.{ 0xd1, 0x01, 0xe4, 0xe7 }, e.buf.items);
}

test "arm32 encoding: ubfx r2, r3, #31, #1" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.ubfx(.r2, .r3, 31, 1);
    // e7e02fd3
    try std.testing.expectEqualSlices(u8, &.{ 0xd3, 0x2f, 0xe0, 0xe7 }, e.buf.items);
}

test "arm32 encoding: sbfx r4, r5, #0, #32" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.sbfx(.r4, .r5, 0, 32);
    // e7bf4055
    try std.testing.expectEqualSlices(u8, &.{ 0x55, 0x40, 0xbf, 0xe7 }, e.buf.items);
}

test "arm32 encoding: sbfx r6, r7, #8, #8" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.sbfx(.r6, .r7, 8, 8);
    // e7a76457
    try std.testing.expectEqualSlices(u8, &.{ 0x57, 0x64, 0xa7, 0xe7 }, e.buf.items);
}

test "arm32 encoding: b .+16" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.b(16);
    // ea000002
    try std.testing.expectEqualSlices(u8, &.{ 0x02, 0x00, 0x00, 0xea }, e.buf.items);
}

test "arm32 encoding: b .-8" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.b(-8);
    // eafffffc
    try std.testing.expectEqualSlices(u8, &.{ 0xfc, 0xff, 0xff, 0xea }, e.buf.items);
}

test "arm32 encoding: b ." {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.b(0);
    // eafffffe
    try std.testing.expectEqualSlices(u8, &.{ 0xfe, 0xff, 0xff, 0xea }, e.buf.items);
}

test "arm32 encoding: bne .+0x100" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.bcond(.ne, 0x100);
    // 1a00003e
    try std.testing.expectEqualSlices(u8, &.{ 0x3e, 0x00, 0x00, 0x1a }, e.buf.items);
}

test "arm32 encoding: ble .-0x1000" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.bcond(.le, -0x1000);
    // dafffbfe
    try std.testing.expectEqualSlices(u8, &.{ 0xfe, 0xfb, 0xff, 0xda }, e.buf.items);
}

test "arm32 encoding: bl .+4096" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.bl(4096);
    // eb0003fe
    try std.testing.expectEqualSlices(u8, &.{ 0xfe, 0x03, 0x00, 0xeb }, e.buf.items);
}

test "arm32 encoding: bl ." {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.bl(0);
    // ebfffffe
    try std.testing.expectEqualSlices(u8, &.{ 0xfe, 0xff, 0xff, 0xeb }, e.buf.items);
}

test "arm32 encoding: bx lr" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.bxReg(.r14);
    // e12fff1e
    try std.testing.expectEqualSlices(u8, &.{ 0x1e, 0xff, 0x2f, 0xe1 }, e.buf.items);
}

test "arm32 encoding: blx r3" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.blxReg(.r3);
    // e12fff33
    try std.testing.expectEqualSlices(u8, &.{ 0x33, 0xff, 0x2f, 0xe1 }, e.buf.items);
}

test "arm32 encoding: udf #0" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.udf(0);
    // e7f000f0
    try std.testing.expectEqualSlices(u8, &.{ 0xf0, 0x00, 0xf0, 0xe7 }, e.buf.items);
}

test "arm32 encoding: udf #0xbeef" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.udf(0xbeef);
    // e7fbeeff
    try std.testing.expectEqualSlices(u8, &.{ 0xff, 0xee, 0xfb, 0xe7 }, e.buf.items);
}

test "arm32 encoding: bkpt #0x1234" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.bkpt(0x1234);
    // e1212374
    try std.testing.expectEqualSlices(u8, &.{ 0x74, 0x23, 0x21, 0xe1 }, e.buf.items);
}

test "arm32 encoding: nop" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.nop();
    // e320f000
    try std.testing.expectEqualSlices(u8, &.{ 0x00, 0xf0, 0x20, 0xe3 }, e.buf.items);
}

test "arm32 encoding: movw r4, #0xfff0; movt r4, #0xfff4; add r4, pc, r4" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    _ = try e.pcRelAddress(.r4);
    // e30f4ff0 e34f4ff4 e08f4004
    try std.testing.expectEqualSlices(u8, &.{ 0xf0, 0x4f, 0x0f, 0xe3, 0xf4, 0x4f, 0x4f, 0xe3, 0x04, 0x40, 0x8f, 0xe0 }, e.buf.items);
}

test "arm32 encoding: ldr r0, [r1]" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.ldrRegMem(.r0, .r1, 0);
    // e5910000
    try std.testing.expectEqualSlices(u8, &.{ 0x00, 0x00, 0x91, 0xe5 }, e.buf.items);
}

test "arm32 encoding: ldr r0, [r11, #-4]" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.ldrRegMem(.r0, .r11, -4);
    // e51b0004
    try std.testing.expectEqualSlices(u8, &.{ 0x04, 0x00, 0x1b, 0xe5 }, e.buf.items);
}

test "arm32 encoding: ldr r12, [sp, #4095]" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.ldrRegMem(.r12, .r13, 4095);
    // e59dcfff
    try std.testing.expectEqualSlices(u8, &.{ 0xff, 0xcf, 0x9d, 0xe5 }, e.buf.items);
}

test "arm32 encoding: str r1, [r11, #-4095]" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.strRegMem(.r1, .r11, -4095);
    // e50b1fff
    try std.testing.expectEqualSlices(u8, &.{ 0xff, 0x1f, 0x0b, 0xe5 }, e.buf.items);
}

test "arm32 encoding: str r10, [r0, #8]" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.strRegMem(.r10, .r0, 8);
    // e580a008
    try std.testing.expectEqualSlices(u8, &.{ 0x08, 0xa0, 0x80, 0xe5 }, e.buf.items);
}

test "arm32 encoding: ldrb r2, [r3, #-1]" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.ldrbRegMem(.r2, .r3, -1);
    // e5532001
    try std.testing.expectEqualSlices(u8, &.{ 0x01, 0x20, 0x53, 0xe5 }, e.buf.items);
}

test "arm32 encoding: ldrb r4, [r5, #100]" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.ldrbRegMem(.r4, .r5, 100);
    // e5d54064
    try std.testing.expectEqualSlices(u8, &.{ 0x64, 0x40, 0xd5, 0xe5 }, e.buf.items);
}

test "arm32 encoding: strb r6, [r7, #4095]" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.strbRegMem(.r6, .r7, 4095);
    // e5c76fff
    try std.testing.expectEqualSlices(u8, &.{ 0xff, 0x6f, 0xc7, 0xe5 }, e.buf.items);
}

test "arm32 encoding: ldrh r0, [r1, #-2]" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.ldrhRegMem(.r0, .r1, -2);
    // e15100b2
    try std.testing.expectEqualSlices(u8, &.{ 0xb2, 0x00, 0x51, 0xe1 }, e.buf.items);
}

test "arm32 encoding: ldrh r8, [r9, #0]" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.ldrhRegMem(.r8, .r9, 0);
    // e1d980b0
    try std.testing.expectEqualSlices(u8, &.{ 0xb0, 0x80, 0xd9, 0xe1 }, e.buf.items);
}

test "arm32 encoding: strh r0, [r1, #254]" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.strhRegMem(.r0, .r1, 254);
    // e1c10fbe
    try std.testing.expectEqualSlices(u8, &.{ 0xbe, 0x0f, 0xc1, 0xe1 }, e.buf.items);
}

test "arm32 encoding: ldrsb r0, [r1, #255]" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.ldrsbRegMem(.r0, .r1, 255);
    // e1d10fdf
    try std.testing.expectEqualSlices(u8, &.{ 0xdf, 0x0f, 0xd1, 0xe1 }, e.buf.items);
}

test "arm32 encoding: ldrsh r0, [r11, #-255]" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.ldrshRegMem(.r0, .r11, -255);
    // e15b0fff
    try std.testing.expectEqualSlices(u8, &.{ 0xff, 0x0f, 0x5b, 0xe1 }, e.buf.items);
}

test "arm32 encoding: ldrd r4, r5, [r11, #-16]" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.ldrdRegMem(.r4, .r11, -16);
    // e14b41d0
    try std.testing.expectEqualSlices(u8, &.{ 0xd0, 0x41, 0x4b, 0xe1 }, e.buf.items);
}

test "arm32 encoding: ldrd r0, r1, [r2]" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.ldrdRegMem(.r0, .r2, 0);
    // e1c200d0
    try std.testing.expectEqualSlices(u8, &.{ 0xd0, 0x00, 0xc2, 0xe1 }, e.buf.items);
}

test "arm32 encoding: strd r2, r3, [sp, #8]" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.strdRegMem(.r2, .r13, 8);
    // e1cd20f8
    try std.testing.expectEqualSlices(u8, &.{ 0xf8, 0x20, 0xcd, 0xe1 }, e.buf.items);
}

test "arm32 encoding: strd r10, r11, [r0, #-255]" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.strdRegMem(.r10, .r0, -255);
    // e140afff
    try std.testing.expectEqualSlices(u8, &.{ 0xff, 0xaf, 0x40, 0xe1 }, e.buf.items);
}

test "arm32 encoding: push {r11, lr}" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.push(GeneralReg.fp.listBit() | GeneralReg.lr.listBit());
    // e92d4800
    try std.testing.expectEqualSlices(u8, &.{ 0x00, 0x48, 0x2d, 0xe9 }, e.buf.items);
}

test "arm32 encoding: push {r4, r5, r6, r7, r8, r9, r10}" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.push(0x07f0);
    // e92d07f0
    try std.testing.expectEqualSlices(u8, &.{ 0xf0, 0x07, 0x2d, 0xe9 }, e.buf.items);
}

test "arm32 encoding: pop {r11, pc}" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.pop(GeneralReg.fp.listBit() | GeneralReg.pc.listBit());
    // e8bd8800
    try std.testing.expectEqualSlices(u8, &.{ 0x00, 0x88, 0xbd, 0xe8 }, e.buf.items);
}

test "arm32 encoding: pop {r4, r5}" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.pop(0x0030);
    // e8bd0030
    try std.testing.expectEqualSlices(u8, &.{ 0x30, 0x00, 0xbd, 0xe8 }, e.buf.items);
}

test "arm32 encoding: vadd.f32 s0, s1, s31" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vaddF32(.s0, .s1, .s31);
    // ee300aaf
    try std.testing.expectEqualSlices(u8, &.{ 0xaf, 0x0a, 0x30, 0xee }, e.buf.items);
}

test "arm32 encoding: vadd.f64 d0, d17, d31" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vaddF64(.d0, .d17, .d31);
    // ee310baf
    try std.testing.expectEqualSlices(u8, &.{ 0xaf, 0x0b, 0x31, 0xee }, e.buf.items);
}

test "arm32 encoding: vsub.f32 s3, s4, s5" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vsubF32(.s3, .s4, .s5);
    // ee721a62
    try std.testing.expectEqualSlices(u8, &.{ 0x62, 0x1a, 0x72, 0xee }, e.buf.items);
}

test "arm32 encoding: vsub.f64 d16, d1, d2" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vsubF64(.d16, .d1, .d2);
    // ee710b42
    try std.testing.expectEqualSlices(u8, &.{ 0x42, 0x0b, 0x71, 0xee }, e.buf.items);
}

test "arm32 encoding: vmul.f32 s30, s31, s0" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vmulF32(.s30, .s31, .s0);
    // ee2ffa80
    try std.testing.expectEqualSlices(u8, &.{ 0x80, 0xfa, 0x2f, 0xee }, e.buf.items);
}

test "arm32 encoding: vmul.f64 d8, d9, d10" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vmulF64(.d8, .d9, .d10);
    // ee298b0a
    try std.testing.expectEqualSlices(u8, &.{ 0x0a, 0x8b, 0x29, 0xee }, e.buf.items);
}

test "arm32 encoding: vdiv.f32 s1, s2, s3" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vdivF32(.s1, .s2, .s3);
    // eec10a21
    try std.testing.expectEqualSlices(u8, &.{ 0x21, 0x0a, 0xc1, 0xee }, e.buf.items);
}

test "arm32 encoding: vdiv.f64 d20, d21, d22" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vdivF64(.d20, .d21, .d22);
    // eec54ba6
    try std.testing.expectEqualSlices(u8, &.{ 0xa6, 0x4b, 0xc5, 0xee }, e.buf.items);
}

test "arm32 encoding: vmov.f32 s3, s4" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vmovF32(.s3, .s4);
    // eef01a42
    try std.testing.expectEqualSlices(u8, &.{ 0x42, 0x1a, 0xf0, 0xee }, e.buf.items);
}

test "arm32 encoding: vmov.f64 d16, d1" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vmovF64(.d16, .d1);
    // eef00b41
    try std.testing.expectEqualSlices(u8, &.{ 0x41, 0x0b, 0xf0, 0xee }, e.buf.items);
}

test "arm32 encoding: vabs.f32 s0, s31" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vabsF32(.s0, .s31);
    // eeb00aef
    try std.testing.expectEqualSlices(u8, &.{ 0xef, 0x0a, 0xb0, 0xee }, e.buf.items);
}

test "arm32 encoding: vabs.f64 d1, d17" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vabsF64(.d1, .d17);
    // eeb01be1
    try std.testing.expectEqualSlices(u8, &.{ 0xe1, 0x1b, 0xb0, 0xee }, e.buf.items);
}

test "arm32 encoding: vneg.f32 s5, s6" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vnegF32(.s5, .s6);
    // eef12a43
    try std.testing.expectEqualSlices(u8, &.{ 0x43, 0x2a, 0xf1, 0xee }, e.buf.items);
}

test "arm32 encoding: vneg.f64 d30, d2" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vnegF64(.d30, .d2);
    // eef1eb42
    try std.testing.expectEqualSlices(u8, &.{ 0x42, 0xeb, 0xf1, 0xee }, e.buf.items);
}

test "arm32 encoding: vsqrt.f32 s7, s8" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vsqrtF32(.s7, .s8);
    // eef13ac4
    try std.testing.expectEqualSlices(u8, &.{ 0xc4, 0x3a, 0xf1, 0xee }, e.buf.items);
}

test "arm32 encoding: vsqrt.f64 d3, d19" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vsqrtF64(.d3, .d19);
    // eeb13be3
    try std.testing.expectEqualSlices(u8, &.{ 0xe3, 0x3b, 0xb1, 0xee }, e.buf.items);
}

test "arm32 encoding: vcmp.f32 s0, s1" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vcmpF32(.s0, .s1);
    // eeb40a60
    try std.testing.expectEqualSlices(u8, &.{ 0x60, 0x0a, 0xb4, 0xee }, e.buf.items);
}

test "arm32 encoding: vcmp.f64 d0, d16" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vcmpF64(.d0, .d16);
    // eeb40b60
    try std.testing.expectEqualSlices(u8, &.{ 0x60, 0x0b, 0xb4, 0xee }, e.buf.items);
}

test "arm32 encoding: vcmpe.f32 s31, s2" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vcmpeF32(.s31, .s2);
    // eef4fac1
    try std.testing.expectEqualSlices(u8, &.{ 0xc1, 0xfa, 0xf4, 0xee }, e.buf.items);
}

test "arm32 encoding: vcmpe.f64 d17, d3" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vcmpeF64(.d17, .d3);
    // eef41bc3
    try std.testing.expectEqualSlices(u8, &.{ 0xc3, 0x1b, 0xf4, 0xee }, e.buf.items);
}

test "arm32 encoding: vcmp.f32 s5, #0" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vcmpZeroF32(.s5);
    // eef52a40
    try std.testing.expectEqualSlices(u8, &.{ 0x40, 0x2a, 0xf5, 0xee }, e.buf.items);
}

test "arm32 encoding: vcmp.f64 d20, #0" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vcmpZeroF64(.d20);
    // eef54b40
    try std.testing.expectEqualSlices(u8, &.{ 0x40, 0x4b, 0xf5, 0xee }, e.buf.items);
}

test "arm32 encoding: vmrs APSR_nzcv, fpscr" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vmrsApsrNzcv();
    // eef1fa10
    try std.testing.expectEqualSlices(u8, &.{ 0x10, 0xfa, 0xf1, 0xee }, e.buf.items);
}

test "arm32 encoding: vcvt.f64.f32 d16, s3" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vcvtF64FromF32(.d16, .s3);
    // eef70ae1
    try std.testing.expectEqualSlices(u8, &.{ 0xe1, 0x0a, 0xf7, 0xee }, e.buf.items);
}

test "arm32 encoding: vcvt.f32.f64 s3, d16" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vcvtF32FromF64(.s3, .d16);
    // eef71be0
    try std.testing.expectEqualSlices(u8, &.{ 0xe0, 0x1b, 0xf7, 0xee }, e.buf.items);
}

test "arm32 encoding: vcvt.s32.f32 s0, s1" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vcvtS32FromF32(.s0, .s1);
    // eebd0ae0
    try std.testing.expectEqualSlices(u8, &.{ 0xe0, 0x0a, 0xbd, 0xee }, e.buf.items);
}

test "arm32 encoding: vcvt.u32.f32 s2, s31" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vcvtU32FromF32(.s2, .s31);
    // eebc1aef
    try std.testing.expectEqualSlices(u8, &.{ 0xef, 0x1a, 0xbc, 0xee }, e.buf.items);
}

test "arm32 encoding: vcvt.s32.f64 s0, d17" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vcvtS32FromF64(.s0, .d17);
    // eebd0be1
    try std.testing.expectEqualSlices(u8, &.{ 0xe1, 0x0b, 0xbd, 0xee }, e.buf.items);
}

test "arm32 encoding: vcvt.u32.f64 s1, d2" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vcvtU32FromF64(.s1, .d2);
    // eefc0bc2
    try std.testing.expectEqualSlices(u8, &.{ 0xc2, 0x0b, 0xfc, 0xee }, e.buf.items);
}

test "arm32 encoding: vcvt.f32.s32 s0, s1" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vcvtF32FromS32(.s0, .s1);
    // eeb80ae0
    try std.testing.expectEqualSlices(u8, &.{ 0xe0, 0x0a, 0xb8, 0xee }, e.buf.items);
}

test "arm32 encoding: vcvt.f32.u32 s3, s2" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vcvtF32FromU32(.s3, .s2);
    // eef81a41
    try std.testing.expectEqualSlices(u8, &.{ 0x41, 0x1a, 0xf8, 0xee }, e.buf.items);
}

test "arm32 encoding: vcvt.f64.s32 d17, s1" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vcvtF64FromS32(.d17, .s1);
    // eef81be0
    try std.testing.expectEqualSlices(u8, &.{ 0xe0, 0x1b, 0xf8, 0xee }, e.buf.items);
}

test "arm32 encoding: vcvt.f64.u32 d2, s31" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vcvtF64FromU32(.d2, .s31);
    // eeb82b6f
    try std.testing.expectEqualSlices(u8, &.{ 0x6f, 0x2b, 0xb8, 0xee }, e.buf.items);
}

test "arm32 encoding: vmov r0, s3" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vmovCoreFromS(.r0, .s3);
    // ee110a90
    try std.testing.expectEqualSlices(u8, &.{ 0x90, 0x0a, 0x11, 0xee }, e.buf.items);
}

test "arm32 encoding: vmov r12, s30" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vmovCoreFromS(.r12, .s30);
    // ee1fca10
    try std.testing.expectEqualSlices(u8, &.{ 0x10, 0xca, 0x1f, 0xee }, e.buf.items);
}

test "arm32 encoding: vmov s3, r0" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vmovSFromCore(.s3, .r0);
    // ee010a90
    try std.testing.expectEqualSlices(u8, &.{ 0x90, 0x0a, 0x01, 0xee }, e.buf.items);
}

test "arm32 encoding: vmov r0, r1, d17" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vmovCorePairFromD(.r0, .r1, .d17);
    // ec510b31
    try std.testing.expectEqualSlices(u8, &.{ 0x31, 0x0b, 0x51, 0xec }, e.buf.items);
}

test "arm32 encoding: vmov r4, r10, d2" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vmovCorePairFromD(.r4, .r10, .d2);
    // ec5a4b12
    try std.testing.expectEqualSlices(u8, &.{ 0x12, 0x4b, 0x5a, 0xec }, e.buf.items);
}

test "arm32 encoding: vmov d17, r0, r1" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vmovDFromCorePair(.d17, .r0, .r1);
    // ec410b31
    try std.testing.expectEqualSlices(u8, &.{ 0x31, 0x0b, 0x41, 0xec }, e.buf.items);
}

test "arm32 encoding: vldr s1, [r11, #-8]" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vldrF32(.s1, .r11, -8);
    // ed5b0a02
    try std.testing.expectEqualSlices(u8, &.{ 0x02, 0x0a, 0x5b, 0xed }, e.buf.items);
}

test "arm32 encoding: vstr s1, [sp, #1020]" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vstrF32(.s1, .r13, 1020);
    // edcd0aff
    try std.testing.expectEqualSlices(u8, &.{ 0xff, 0x0a, 0xcd, 0xed }, e.buf.items);
}

test "arm32 encoding: vldr d17, [r11, #-1020]" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vldrF64(.d17, .r11, -1020);
    // ed5b1bff
    try std.testing.expectEqualSlices(u8, &.{ 0xff, 0x1b, 0x5b, 0xed }, e.buf.items);
}

test "arm32 encoding: vstr d8, [r0]" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vstrF64(.d8, .r0, 0);
    // ed808b00
    try std.testing.expectEqualSlices(u8, &.{ 0x00, 0x8b, 0x80, 0xed }, e.buf.items);
}

test "arm32 encoding: vpush {d8-d15}" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vpush(.d8, 8);
    // ed2d8b10
    try std.testing.expectEqualSlices(u8, &.{ 0x10, 0x8b, 0x2d, 0xed }, e.buf.items);
}

test "arm32 encoding: vpush {d16}" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vpush(.d16, 1);
    // ed6d0b02
    try std.testing.expectEqualSlices(u8, &.{ 0x02, 0x0b, 0x6d, 0xed }, e.buf.items);
}

test "arm32 encoding: vpop {d8-d15}" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vpop(.d8, 8);
    // ecbd8b10
    try std.testing.expectEqualSlices(u8, &.{ 0x10, 0x8b, 0xbd, 0xec }, e.buf.items);
}

test "arm32 encoding: vpop {d17-d20}" {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    try e.vpop(.d17, 4);
    // ecfd1b08
    try std.testing.expectEqualSlices(u8, &.{ 0x08, 0x1b, 0xfd, 0xec }, e.buf.items);
}
