//! Byte-exact A32 encoding tests for arm32 `Emit`.
//!
//! GENERATED by ci/arm32_encoding_oracle.py from ci/arm32_encoding_oracle.s;
//! do not edit. The expected words are what `zig cc -target
//! arm-linux-musleabihf` assembles each entry to. Regenerate with
//! `python3 ci/arm32_encoding_oracle.py`; CI runs it with `--check`.

const std = @import("std");
const emit = @import("Emit.zig");
const E = emit.Emit(.arm32musl);
const ModImm = emit.ModImm;
const GeneralReg = E.GeneralReg;
const Operand2 = emit.Operand2;

/// Call `method` with `args` on a fresh emitter and expect exactly the
/// little-endian `words`.
fn expectEncoding(comptime method: anytype, args: anytype, words: []const u32) !void {
    var e = E.init(std.testing.allocator);
    defer e.deinit();
    _ = try @call(.auto, method, .{&e} ++ args);
    try std.testing.expectEqual(words.len * 4, e.buf.items.len);
    for (words, 0..) |word, i| {
        const got = std.mem.readInt(u32, e.buf.items[i * 4 ..][0..4], .little);
        if (got != word) {
            std.debug.print("word {d}: expected 0x{x:0>8}, found 0x{x:0>8}\n", .{ i, word, got });
            return error.TestExpectedEqual;
        }
    }
}

test "arm32 encoding: mov r0, r1" {
    try expectEncoding(E.movRegReg, .{ .r0, .r1 }, &.{0xe1a00001});
}
test "arm32 encoding: mov r11, sp" {
    try expectEncoding(E.movRegReg, .{ .r11, .r13 }, &.{0xe1a0b00d});
}
test "arm32 encoding: movne r3, r12" {
    try expectEncoding(E.movRegRegCond, .{ .ne, .r3, .r12 }, &.{0x11a0300c});
}
test "arm32 encoding: mov r2, #255" {
    try expectEncoding(E.movRegModImm, .{ .r2, ModImm.of(255) }, &.{0xe3a020ff});
}
test "arm32 encoding: mov r2, #0xff000000" {
    try expectEncoding(E.movRegModImm, .{ .r2, ModImm.of(0xff000000) }, &.{0xe3a024ff});
}
test "arm32 encoding: mov r9, #0x3fc" {
    try expectEncoding(E.movRegModImm, .{ .r9, ModImm.of(0x3fc) }, &.{0xe3a09fff});
}
test "arm32 encoding: moveq r0, #1" {
    try expectEncoding(E.movRegModImmCond, .{ .eq, .r0, ModImm.of(1) }, &.{0x03a00001});
}
test "arm32 encoding: movlt r10, #0" {
    try expectEncoding(E.movRegModImmCond, .{ .lt, .r10, ModImm.of(0) }, &.{0xb3a0a000});
}
test "arm32 encoding: mvn r5, #0" {
    try expectEncoding(E.mvnRegModImm, .{ .r5, ModImm.of(0) }, &.{0xe3e05000});
}
test "arm32 encoding: mvn r5, r6" {
    try expectEncoding(E.mvnRegReg, .{ .r5, .r6 }, &.{0xe1e05006});
}
test "arm32 encoding: movw r7, #0x1234" {
    try expectEncoding(E.movw, .{ .r7, 0x1234 }, &.{0xe3017234});
}
test "arm32 encoding: movw r12, #0xffff" {
    try expectEncoding(E.movw, .{ .r12, 0xffff }, &.{0xe30fcfff});
}
test "arm32 encoding: movt r7, #0xabcd" {
    try expectEncoding(E.movt, .{ .r7, 0xabcd }, &.{0xe34a7bcd});
}
test "arm32 encoding: mov r0, #1024" {
    try expectEncoding(E.movRegImm32, .{ .r0, 0x400 }, &.{0xe3a00b01});
}
test "arm32 encoding: mvn r1, #255" {
    try expectEncoding(E.movRegImm32, .{ .r1, 0xffffff00 }, &.{0xe3e010ff});
}
test "arm32 encoding: movw r2, #0xabcd" {
    try expectEncoding(E.movRegImm32, .{ .r2, 0xabcd }, &.{0xe30a2bcd});
}
test "arm32 encoding: movw r3, #0x5678; movt r3, #0x1234" {
    try expectEncoding(E.movRegImm32, .{ .r3, 0x12345678 }, &.{ 0xe3053678, 0xe3413234 });
}
test "arm32 encoding: movw r4, #0; movt r4, #0x1235" {
    try expectEncoding(E.movRegImm32, .{ .r4, 0x12350000 }, &.{ 0xe3004000, 0xe3414235 });
}
test "arm32 encoding: add r0, r1, r2" {
    try expectEncoding(E.addRegRegReg, .{ .r0, .r1, .r2 }, &.{0xe0810002});
}
test "arm32 encoding: adds r3, r4, r5" {
    try expectEncoding(E.addsRegRegReg, .{ .r3, .r4, .r5 }, &.{0xe0943005});
}
test "arm32 encoding: adc r6, r7, r8" {
    try expectEncoding(E.adcRegRegReg, .{ .r6, .r7, .r8 }, &.{0xe0a76008});
}
test "arm32 encoding: adcs r9, r10, r11" {
    try expectEncoding(E.adcsRegRegReg, .{ .r9, .r10, .r11 }, &.{0xe0ba900b});
}
test "arm32 encoding: sub r0, r1, r2" {
    try expectEncoding(E.subRegRegReg, .{ .r0, .r1, .r2 }, &.{0xe0410002});
}
test "arm32 encoding: subs r12, r0, r1" {
    try expectEncoding(E.subsRegRegReg, .{ .r12, .r0, .r1 }, &.{0xe050c001});
}
test "arm32 encoding: sbc r2, r3, r4" {
    try expectEncoding(E.sbcRegRegReg, .{ .r2, .r3, .r4 }, &.{0xe0c32004});
}
test "arm32 encoding: sbcs r5, r6, r7" {
    try expectEncoding(E.sbcsRegRegReg, .{ .r5, .r6, .r7 }, &.{0xe0d65007});
}
test "arm32 encoding: add r0, r11, #4080" {
    try expectEncoding(E.addRegRegModImm, .{ .r0, .r11, ModImm.of(4080) }, &.{0xe28b0eff});
}
test "arm32 encoding: add r12, sp, #8" {
    try expectEncoding(E.addRegRegModImm, .{ .r12, .r13, ModImm.of(8) }, &.{0xe28dc008});
}
test "arm32 encoding: adds r1, r1, #1" {
    try expectEncoding(E.addsRegRegModImm, .{ .r1, .r1, ModImm.of(1) }, &.{0xe2911001});
}
test "arm32 encoding: sub sp, sp, #256" {
    try expectEncoding(E.subRegRegModImm, .{ .r13, .r13, ModImm.of(256) }, &.{0xe24ddc01});
}
test "arm32 encoding: sub r12, r11, #0x10000" {
    try expectEncoding(E.subRegRegModImm, .{ .r12, .r11, ModImm.of(0x10000) }, &.{0xe24bc801});
}
test "arm32 encoding: subs r3, r2, #32" {
    try expectEncoding(E.subsRegRegModImm, .{ .r3, .r2, ModImm.of(32) }, &.{0xe2523020});
}
test "arm32 encoding: rsb r0, r1, #0" {
    try expectEncoding(E.rsbRegRegModImm, .{ .r0, .r1, ModImm.of(0) }, &.{0xe2610000});
}
test "arm32 encoding: rsb r12, r2, #32" {
    try expectEncoding(E.rsbRegRegModImm, .{ .r12, .r2, ModImm.of(32) }, &.{0xe262c020});
}
test "arm32 encoding: rsbs r0, r0, #0" {
    try expectEncoding(E.rsbsRegRegModImm, .{ .r0, .r0, ModImm.of(0) }, &.{0xe2700000});
}
test "arm32 encoding: rsc r1, r1, #0" {
    try expectEncoding(E.rscRegRegModImm, .{ .r1, .r1, ModImm.of(0) }, &.{0xe2e11000});
}
test "arm32 encoding: and r0, r1, r2" {
    try expectEncoding(E.andRegRegReg, .{ .r0, .r1, .r2 }, &.{0xe0010002});
}
test "arm32 encoding: orr r3, r4, r5" {
    try expectEncoding(E.orrRegRegReg, .{ .r3, .r4, .r5 }, &.{0xe1843005});
}
test "arm32 encoding: eor r6, r7, r8" {
    try expectEncoding(E.eorRegRegReg, .{ .r6, .r7, .r8 }, &.{0xe0276008});
}
test "arm32 encoding: bic r9, r10, r12" {
    try expectEncoding(E.bicRegRegReg, .{ .r9, .r10, .r12 }, &.{0xe1ca900c});
}
test "arm32 encoding: and r0, r1, #255" {
    try expectEncoding(E.andRegRegModImm, .{ .r0, .r1, ModImm.of(255) }, &.{0xe20100ff});
}
test "arm32 encoding: orr r0, r0, #0x80000000" {
    try expectEncoding(E.orrRegRegModImm, .{ .r0, .r0, ModImm.of(0x80000000) }, &.{0xe3800102});
}
test "arm32 encoding: eor r2, r2, #1" {
    try expectEncoding(E.eorRegRegModImm, .{ .r2, .r2, ModImm.of(1) }, &.{0xe2222001});
}
test "arm32 encoding: bic r3, r3, #0xff00" {
    try expectEncoding(E.bicRegRegModImm, .{ .r3, .r3, ModImm.of(0xff00) }, &.{0xe3c33cff});
}
test "arm32 encoding: cmp r0, r1" {
    try expectEncoding(E.cmpRegReg, .{ .r0, .r1 }, &.{0xe1500001});
}
test "arm32 encoding: cmp r10, r12" {
    try expectEncoding(E.cmpRegReg, .{ .r10, .r12 }, &.{0xe15a000c});
}
test "arm32 encoding: cmp r0, #0" {
    try expectEncoding(E.cmpRegModImm, .{ .r0, ModImm.of(0) }, &.{0xe3500000});
}
test "arm32 encoding: cmp r7, #0xff0" {
    try expectEncoding(E.cmpRegModImm, .{ .r7, ModImm.of(0xff0) }, &.{0xe3570eff});
}
test "arm32 encoding: cmn r0, #1" {
    try expectEncoding(E.cmnRegModImm, .{ .r0, ModImm.of(1) }, &.{0xe3700001});
}
test "arm32 encoding: tst r0, r1" {
    try expectEncoding(E.tstRegReg, .{ .r0, .r1 }, &.{0xe1100001});
}
test "arm32 encoding: tst r2, #1" {
    try expectEncoding(E.tstRegModImm, .{ .r2, ModImm.of(1) }, &.{0xe3120001});
}
test "arm32 encoding: teq r3, r4" {
    try expectEncoding(E.teqRegReg, .{ .r3, .r4 }, &.{0xe1330004});
}
test "arm32 encoding: orr r1, r1, r0, lsr r12" {
    try expectEncoding(E.dataProc, .{ .al, .orr, false, .r1, .r1, Operand2{ .shift_reg = .{ .rm = .r0, .kind = .lsr, .rs = .r12 } } }, &.{0xe1811c30});
}
test "arm32 encoding: subgt r0, r1, r2, lsl #3" {
    try expectEncoding(E.dataProc, .{ .gt, .sub, false, .r0, .r1, Operand2{ .shift_imm = .{ .rm = .r2, .kind = .lsl, .amount = 3 } } }, &.{0xc0410182});
}
test "arm32 encoding: addsne r4, r5, r6, asr #32" {
    try expectEncoding(E.dataProc, .{ .ne, .add, true, .r4, .r5, Operand2{ .shift_imm = .{ .rm = .r6, .kind = .asr, .amount = 32 } } }, &.{0x10954046});
}
test "arm32 encoding: lslpl r1, r0, r3" {
    try expectEncoding(E.dataProc, .{ .pl, .mov, false, .r1, .r0, Operand2{ .shift_reg = .{ .rm = .r0, .kind = .lsl, .rs = .r3 } } }, &.{0x51a01310});
}
test "arm32 encoding: cmp r1, r3, ror #7" {
    try expectEncoding(E.dataProc, .{ .al, .cmp, true, .r0, .r1, Operand2{ .shift_imm = .{ .rm = .r3, .kind = .ror, .amount = 7 } } }, &.{0xe15103e3});
}
test "arm32 encoding: bichi r2, r2, #3" {
    try expectEncoding(E.dataProc, .{ .hi, .bic, false, .r2, .r2, Operand2{ .imm = ModImm.of(3) } }, &.{0x83c22003});
}
test "arm32 encoding: lsl r0, r1, #31" {
    try expectEncoding(E.lslRegRegImm, .{ .r0, .r1, 31 }, &.{0xe1a00f81});
}
test "arm32 encoding: lsl r8, r9, #1" {
    try expectEncoding(E.lslRegRegImm, .{ .r8, .r9, 1 }, &.{0xe1a08089});
}
test "arm32 encoding: lsr r0, r1, #32" {
    try expectEncoding(E.lsrRegRegImm, .{ .r0, .r1, 32 }, &.{0xe1a00021});
}
test "arm32 encoding: lsr r2, r3, #16" {
    try expectEncoding(E.lsrRegRegImm, .{ .r2, .r3, 16 }, &.{0xe1a02823});
}
test "arm32 encoding: asr r0, r1, #1" {
    try expectEncoding(E.asrRegRegImm, .{ .r0, .r1, 1 }, &.{0xe1a000c1});
}
test "arm32 encoding: asr r4, r5, #32" {
    try expectEncoding(E.asrRegRegImm, .{ .r4, .r5, 32 }, &.{0xe1a04045});
}
test "arm32 encoding: ror r0, r1, #8" {
    try expectEncoding(E.rorRegRegImm, .{ .r0, .r1, 8 }, &.{0xe1a00461});
}
test "arm32 encoding: lsl r0, r1, r2" {
    try expectEncoding(E.lslRegRegReg, .{ .r0, .r1, .r2 }, &.{0xe1a00211});
}
test "arm32 encoding: lsr r3, r4, r12" {
    try expectEncoding(E.lsrRegRegReg, .{ .r3, .r4, .r12 }, &.{0xe1a03c34});
}
test "arm32 encoding: asr r5, r6, r7" {
    try expectEncoding(E.asrRegRegReg, .{ .r5, .r6, .r7 }, &.{0xe1a05756});
}
test "arm32 encoding: ror r8, r9, r10" {
    try expectEncoding(E.rorRegRegReg, .{ .r8, .r9, .r10 }, &.{0xe1a08a79});
}
test "arm32 encoding: mul r0, r1, r2" {
    try expectEncoding(E.mulRegRegReg, .{ .r0, .r1, .r2 }, &.{0xe0000291});
}
test "arm32 encoding: mul r10, r9, r8" {
    try expectEncoding(E.mulRegRegReg, .{ .r10, .r9, .r8 }, &.{0xe00a0899});
}
test "arm32 encoding: mla r0, r1, r2, r3" {
    try expectEncoding(E.mlaRegRegRegReg, .{ .r0, .r1, .r2, .r3 }, &.{0xe0203291});
}
test "arm32 encoding: mls r4, r5, r6, r7" {
    try expectEncoding(E.mlsRegRegRegReg, .{ .r4, .r5, .r6, .r7 }, &.{0xe0647695});
}
test "arm32 encoding: umull r0, r1, r2, r3" {
    try expectEncoding(E.umull, .{ .r0, .r1, .r2, .r3 }, &.{0xe0810392});
}
test "arm32 encoding: umlal r4, r5, r6, r7" {
    try expectEncoding(E.umlal, .{ .r4, .r5, .r6, .r7 }, &.{0xe0a54796});
}
test "arm32 encoding: umaal r0, r1, r2, r3" {
    try expectEncoding(E.umaal, .{ .r0, .r1, .r2, .r3 }, &.{0xe0410392});
}
test "arm32 encoding: umaal r10, r12, r9, r8" {
    try expectEncoding(E.umaal, .{ .r10, .r12, .r9, .r8 }, &.{0xe04ca899});
}
test "arm32 encoding: smull r8, r9, r10, r12" {
    try expectEncoding(E.smull, .{ .r8, .r9, .r10, .r12 }, &.{0xe0c98c9a});
}
test "arm32 encoding: smlal r0, r12, r2, r3" {
    try expectEncoding(E.smlal, .{ .r0, .r12, .r2, .r3 }, &.{0xe0ec0392});
}
test "arm32 encoding: clz r0, r1" {
    try expectEncoding(E.clzRegReg, .{ .r0, .r1 }, &.{0xe16f0f11});
}
test "arm32 encoding: clz r12, r10" {
    try expectEncoding(E.clzRegReg, .{ .r12, .r10 }, &.{0xe16fcf1a});
}
test "arm32 encoding: rbit r2, r3" {
    try expectEncoding(E.rbitRegReg, .{ .r2, .r3 }, &.{0xe6ff2f33});
}
test "arm32 encoding: rev r4, r5" {
    try expectEncoding(E.revRegReg, .{ .r4, .r5 }, &.{0xe6bf4f35});
}
test "arm32 encoding: rev16 r6, r7" {
    try expectEncoding(E.rev16RegReg, .{ .r6, .r7 }, &.{0xe6bf6fb7});
}
test "arm32 encoding: uxtb r0, r1" {
    try expectEncoding(E.uxtbRegReg, .{ .r0, .r1 }, &.{0xe6ef0071});
}
test "arm32 encoding: uxth r2, r3" {
    try expectEncoding(E.uxthRegReg, .{ .r2, .r3 }, &.{0xe6ff2073});
}
test "arm32 encoding: sxtb r4, r5" {
    try expectEncoding(E.sxtbRegReg, .{ .r4, .r5 }, &.{0xe6af4075});
}
test "arm32 encoding: sxth r10, r12" {
    try expectEncoding(E.sxthRegReg, .{ .r10, .r12 }, &.{0xe6bfa07c});
}
test "arm32 encoding: ubfx r0, r1, #3, #5" {
    try expectEncoding(E.ubfx, .{ .r0, .r1, 3, 5 }, &.{0xe7e401d1});
}
test "arm32 encoding: ubfx r2, r3, #31, #1" {
    try expectEncoding(E.ubfx, .{ .r2, .r3, 31, 1 }, &.{0xe7e02fd3});
}
test "arm32 encoding: sbfx r4, r5, #0, #32" {
    try expectEncoding(E.sbfx, .{ .r4, .r5, 0, 32 }, &.{0xe7bf4055});
}
test "arm32 encoding: sbfx r6, r7, #8, #8" {
    try expectEncoding(E.sbfx, .{ .r6, .r7, 8, 8 }, &.{0xe7a76457});
}
test "arm32 encoding: b .+16" {
    try expectEncoding(E.b, .{16}, &.{0xea000002});
}
test "arm32 encoding: b .-8" {
    try expectEncoding(E.b, .{-8}, &.{0xeafffffc});
}
test "arm32 encoding: b ." {
    try expectEncoding(E.b, .{0}, &.{0xeafffffe});
}
test "arm32 encoding: bne .+0x100" {
    try expectEncoding(E.bcond, .{ .ne, 0x100 }, &.{0x1a00003e});
}
test "arm32 encoding: ble .-0x1000" {
    try expectEncoding(E.bcond, .{ .le, -0x1000 }, &.{0xdafffbfe});
}
test "arm32 encoding: bl .+4096" {
    try expectEncoding(E.bl, .{4096}, &.{0xeb0003fe});
}
test "arm32 encoding: bl ." {
    try expectEncoding(E.bl, .{0}, &.{0xebfffffe});
}
test "arm32 encoding: bx lr" {
    try expectEncoding(E.bxReg, .{.r14}, &.{0xe12fff1e});
}
test "arm32 encoding: bx lr (2)" {
    try expectEncoding(E.ret, .{}, &.{0xe12fff1e});
}
test "arm32 encoding: blx r3" {
    try expectEncoding(E.blxReg, .{.r3}, &.{0xe12fff33});
}
test "arm32 encoding: udf #0" {
    try expectEncoding(E.udf, .{0}, &.{0xe7f000f0});
}
test "arm32 encoding: udf #0xbeef" {
    try expectEncoding(E.udf, .{0xbeef}, &.{0xe7fbeeff});
}
test "arm32 encoding: bkpt #0x1234" {
    try expectEncoding(E.bkpt, .{0x1234}, &.{0xe1212374});
}
test "arm32 encoding: nop" {
    try expectEncoding(E.nop, .{}, &.{0xe320f000});
}
test "arm32 encoding: movw r4, #0xfff0; movt r4, #0xfff4; add r4, pc, r4" {
    try expectEncoding(E.pcRelAddress, .{.r4}, &.{ 0xe30f4ff0, 0xe34f4ff4, 0xe08f4004 });
}
test "arm32 encoding: ldr r0, [r1]" {
    try expectEncoding(E.ldrRegMem, .{ .r0, .r1, 0 }, &.{0xe5910000});
}
test "arm32 encoding: ldr r0, [r11, #-4]" {
    try expectEncoding(E.ldrRegMem, .{ .r0, .r11, -4 }, &.{0xe51b0004});
}
test "arm32 encoding: ldr r12, [sp, #4095]" {
    try expectEncoding(E.ldrRegMem, .{ .r12, .r13, 4095 }, &.{0xe59dcfff});
}
test "arm32 encoding: str r1, [r11, #-4095]" {
    try expectEncoding(E.strRegMem, .{ .r1, .r11, -4095 }, &.{0xe50b1fff});
}
test "arm32 encoding: str r10, [r0, #8]" {
    try expectEncoding(E.strRegMem, .{ .r10, .r0, 8 }, &.{0xe580a008});
}
test "arm32 encoding: ldrb r2, [r3, #-1]" {
    try expectEncoding(E.ldrbRegMem, .{ .r2, .r3, -1 }, &.{0xe5532001});
}
test "arm32 encoding: ldrb r4, [r5, #100]" {
    try expectEncoding(E.ldrbRegMem, .{ .r4, .r5, 100 }, &.{0xe5d54064});
}
test "arm32 encoding: strb r6, [r7, #4095]" {
    try expectEncoding(E.strbRegMem, .{ .r6, .r7, 4095 }, &.{0xe5c76fff});
}
test "arm32 encoding: ldrh r0, [r1, #-2]" {
    try expectEncoding(E.ldrhRegMem, .{ .r0, .r1, -2 }, &.{0xe15100b2});
}
test "arm32 encoding: ldrh r8, [r9, #0]" {
    try expectEncoding(E.ldrhRegMem, .{ .r8, .r9, 0 }, &.{0xe1d980b0});
}
test "arm32 encoding: strh r0, [r1, #254]" {
    try expectEncoding(E.strhRegMem, .{ .r0, .r1, 254 }, &.{0xe1c10fbe});
}
test "arm32 encoding: ldrsb r0, [r1, #255]" {
    try expectEncoding(E.ldrsbRegMem, .{ .r0, .r1, 255 }, &.{0xe1d10fdf});
}
test "arm32 encoding: ldrsh r0, [r11, #-255]" {
    try expectEncoding(E.ldrshRegMem, .{ .r0, .r11, -255 }, &.{0xe15b0fff});
}
test "arm32 encoding: ldrd r4, r5, [r11, #-16]" {
    try expectEncoding(E.ldrdRegMem, .{ .r4, .r11, -16 }, &.{0xe14b41d0});
}
test "arm32 encoding: ldrd r0, r1, [r2]" {
    try expectEncoding(E.ldrdRegMem, .{ .r0, .r2, 0 }, &.{0xe1c200d0});
}
test "arm32 encoding: strd r2, r3, [sp, #8]" {
    try expectEncoding(E.strdRegMem, .{ .r2, .r13, 8 }, &.{0xe1cd20f8});
}
test "arm32 encoding: strd r10, r11, [r0, #-255]" {
    try expectEncoding(E.strdRegMem, .{ .r10, .r0, -255 }, &.{0xe140afff});
}
test "arm32 encoding: push {r11, lr}" {
    try expectEncoding(E.push, .{GeneralReg.fp.listBit() | GeneralReg.lr.listBit()}, &.{0xe92d4800});
}
test "arm32 encoding: push {r4, r5, r6, r7, r8, r9, r10}" {
    try expectEncoding(E.push, .{0x07f0}, &.{0xe92d07f0});
}
test "arm32 encoding: pop {r11, pc}" {
    try expectEncoding(E.pop, .{GeneralReg.fp.listBit() | GeneralReg.pc.listBit()}, &.{0xe8bd8800});
}
test "arm32 encoding: pop {r4, r5}" {
    try expectEncoding(E.pop, .{0x0030}, &.{0xe8bd0030});
}
test "arm32 encoding: vadd.f32 s0, s1, s31" {
    try expectEncoding(E.vaddF32, .{ .s0, .s1, .s31 }, &.{0xee300aaf});
}
test "arm32 encoding: vadd.f64 d0, d17, d31" {
    try expectEncoding(E.vaddF64, .{ .d0, .d17, .d31 }, &.{0xee310baf});
}
test "arm32 encoding: vsub.f32 s3, s4, s5" {
    try expectEncoding(E.vsubF32, .{ .s3, .s4, .s5 }, &.{0xee721a62});
}
test "arm32 encoding: vsub.f64 d16, d1, d2" {
    try expectEncoding(E.vsubF64, .{ .d16, .d1, .d2 }, &.{0xee710b42});
}
test "arm32 encoding: vmul.f32 s30, s31, s0" {
    try expectEncoding(E.vmulF32, .{ .s30, .s31, .s0 }, &.{0xee2ffa80});
}
test "arm32 encoding: vmul.f64 d8, d9, d10" {
    try expectEncoding(E.vmulF64, .{ .d8, .d9, .d10 }, &.{0xee298b0a});
}
test "arm32 encoding: vdiv.f32 s1, s2, s3" {
    try expectEncoding(E.vdivF32, .{ .s1, .s2, .s3 }, &.{0xeec10a21});
}
test "arm32 encoding: vdiv.f64 d20, d21, d22" {
    try expectEncoding(E.vdivF64, .{ .d20, .d21, .d22 }, &.{0xeec54ba6});
}
test "arm32 encoding: vmov.f32 s3, s4" {
    try expectEncoding(E.vmovF32, .{ .s3, .s4 }, &.{0xeef01a42});
}
test "arm32 encoding: vmov.f64 d16, d1" {
    try expectEncoding(E.vmovF64, .{ .d16, .d1 }, &.{0xeef00b41});
}
test "arm32 encoding: vabs.f32 s0, s31" {
    try expectEncoding(E.vabsF32, .{ .s0, .s31 }, &.{0xeeb00aef});
}
test "arm32 encoding: vabs.f64 d1, d17" {
    try expectEncoding(E.vabsF64, .{ .d1, .d17 }, &.{0xeeb01be1});
}
test "arm32 encoding: vneg.f32 s5, s6" {
    try expectEncoding(E.vnegF32, .{ .s5, .s6 }, &.{0xeef12a43});
}
test "arm32 encoding: vneg.f64 d30, d2" {
    try expectEncoding(E.vnegF64, .{ .d30, .d2 }, &.{0xeef1eb42});
}
test "arm32 encoding: vsqrt.f32 s7, s8" {
    try expectEncoding(E.vsqrtF32, .{ .s7, .s8 }, &.{0xeef13ac4});
}
test "arm32 encoding: vsqrt.f64 d3, d19" {
    try expectEncoding(E.vsqrtF64, .{ .d3, .d19 }, &.{0xeeb13be3});
}
test "arm32 encoding: vcmp.f32 s0, s1" {
    try expectEncoding(E.vcmpF32, .{ .s0, .s1 }, &.{0xeeb40a60});
}
test "arm32 encoding: vcmp.f64 d0, d16" {
    try expectEncoding(E.vcmpF64, .{ .d0, .d16 }, &.{0xeeb40b60});
}
test "arm32 encoding: vcmpe.f32 s31, s2" {
    try expectEncoding(E.vcmpeF32, .{ .s31, .s2 }, &.{0xeef4fac1});
}
test "arm32 encoding: vcmpe.f64 d17, d3" {
    try expectEncoding(E.vcmpeF64, .{ .d17, .d3 }, &.{0xeef41bc3});
}
test "arm32 encoding: vcmp.f32 s5, #0" {
    try expectEncoding(E.vcmpZeroF32, .{.s5}, &.{0xeef52a40});
}
test "arm32 encoding: vcmp.f64 d20, #0" {
    try expectEncoding(E.vcmpZeroF64, .{.d20}, &.{0xeef54b40});
}
test "arm32 encoding: vmrs APSR_nzcv, fpscr" {
    try expectEncoding(E.vmrsApsrNzcv, .{}, &.{0xeef1fa10});
}
test "arm32 encoding: vcvt.f64.f32 d16, s3" {
    try expectEncoding(E.vcvtF64FromF32, .{ .d16, .s3 }, &.{0xeef70ae1});
}
test "arm32 encoding: vcvt.f32.f64 s3, d16" {
    try expectEncoding(E.vcvtF32FromF64, .{ .s3, .d16 }, &.{0xeef71be0});
}
test "arm32 encoding: vcvt.s32.f32 s0, s1" {
    try expectEncoding(E.vcvtS32FromF32, .{ .s0, .s1 }, &.{0xeebd0ae0});
}
test "arm32 encoding: vcvt.u32.f32 s2, s31" {
    try expectEncoding(E.vcvtU32FromF32, .{ .s2, .s31 }, &.{0xeebc1aef});
}
test "arm32 encoding: vcvt.s32.f64 s0, d17" {
    try expectEncoding(E.vcvtS32FromF64, .{ .s0, .d17 }, &.{0xeebd0be1});
}
test "arm32 encoding: vcvt.u32.f64 s1, d2" {
    try expectEncoding(E.vcvtU32FromF64, .{ .s1, .d2 }, &.{0xeefc0bc2});
}
test "arm32 encoding: vcvt.f32.s32 s0, s1" {
    try expectEncoding(E.vcvtF32FromS32, .{ .s0, .s1 }, &.{0xeeb80ae0});
}
test "arm32 encoding: vcvt.f32.u32 s3, s2" {
    try expectEncoding(E.vcvtF32FromU32, .{ .s3, .s2 }, &.{0xeef81a41});
}
test "arm32 encoding: vcvt.f64.s32 d17, s1" {
    try expectEncoding(E.vcvtF64FromS32, .{ .d17, .s1 }, &.{0xeef81be0});
}
test "arm32 encoding: vcvt.f64.u32 d2, s31" {
    try expectEncoding(E.vcvtF64FromU32, .{ .d2, .s31 }, &.{0xeeb82b6f});
}
test "arm32 encoding: vmov r0, s3" {
    try expectEncoding(E.vmovCoreFromS, .{ .r0, .s3 }, &.{0xee110a90});
}
test "arm32 encoding: vmov r12, s30" {
    try expectEncoding(E.vmovCoreFromS, .{ .r12, .s30 }, &.{0xee1fca10});
}
test "arm32 encoding: vmov s3, r0" {
    try expectEncoding(E.vmovSFromCore, .{ .s3, .r0 }, &.{0xee010a90});
}
test "arm32 encoding: vmov r0, r1, d17" {
    try expectEncoding(E.vmovCorePairFromD, .{ .r0, .r1, .d17 }, &.{0xec510b31});
}
test "arm32 encoding: vmov r4, r10, d2" {
    try expectEncoding(E.vmovCorePairFromD, .{ .r4, .r10, .d2 }, &.{0xec5a4b12});
}
test "arm32 encoding: vmov d17, r0, r1" {
    try expectEncoding(E.vmovDFromCorePair, .{ .d17, .r0, .r1 }, &.{0xec410b31});
}
test "arm32 encoding: vldr s1, [r11, #-8]" {
    try expectEncoding(E.vldrF32, .{ .s1, .r11, -8 }, &.{0xed5b0a02});
}
test "arm32 encoding: vstr s1, [sp, #1020]" {
    try expectEncoding(E.vstrF32, .{ .s1, .r13, 1020 }, &.{0xedcd0aff});
}
test "arm32 encoding: vldr d17, [r11, #-1020]" {
    try expectEncoding(E.vldrF64, .{ .d17, .r11, -1020 }, &.{0xed5b1bff});
}
test "arm32 encoding: vstr d8, [r0]" {
    try expectEncoding(E.vstrF64, .{ .d8, .r0, 0 }, &.{0xed808b00});
}
test "arm32 encoding: vpush {d8-d15}" {
    try expectEncoding(E.vpush, .{ .d8, 8 }, &.{0xed2d8b10});
}
test "arm32 encoding: vpush {d16}" {
    try expectEncoding(E.vpush, .{ .d16, 1 }, &.{0xed6d0b02});
}
test "arm32 encoding: vpop {d8-d15}" {
    try expectEncoding(E.vpop, .{ .d8, 8 }, &.{0xecbd8b10});
}
test "arm32 encoding: vpop {d17-d20}" {
    try expectEncoding(E.vpop, .{ .d17, 4 }, &.{0xecfd1b08});
}
test "arm32 encoding: vadd.i8 q0, q1, q2" {
    try expectEncoding(E.neonThreeSameQ, .{ .vadd, .i8, .q0, .q1, .q2 }, &.{0xf2020844});
}
test "arm32 encoding: vadd.i64 q8, q9, q15" {
    try expectEncoding(E.neonThreeSameQ, .{ .vadd, .i64, .q8, .q9, .q15 }, &.{0xf27208ee});
}
test "arm32 encoding: vsub.i16 q3, q4, q5" {
    try expectEncoding(E.neonThreeSameQ, .{ .vsub, .i16, .q3, .q4, .q5 }, &.{0xf318684a});
}
test "arm32 encoding: vsub.i64 q0, q0, q1" {
    try expectEncoding(E.neonThreeSameQ, .{ .vsub, .i64, .q0, .q0, .q1 }, &.{0xf3300842});
}
test "arm32 encoding: vqadd.s8 q0, q1, q2" {
    try expectEncoding(E.neonThreeSameQ, .{ .vqadd_s, .i8, .q0, .q1, .q2 }, &.{0xf2020054});
}
test "arm32 encoding: vqadd.u64 q10, q11, q12" {
    try expectEncoding(E.neonThreeSameQ, .{ .vqadd_u, .i64, .q10, .q11, .q12 }, &.{0xf37640f8});
}
test "arm32 encoding: vqsub.s32 q1, q2, q3" {
    try expectEncoding(E.neonThreeSameQ, .{ .vqsub_s, .i32, .q1, .q2, .q3 }, &.{0xf2242256});
}
test "arm32 encoding: vqsub.u64 q0, q1, q2" {
    try expectEncoding(E.neonThreeSameQ, .{ .vqsub_u, .i64, .q0, .q1, .q2 }, &.{0xf3320254});
}
test "arm32 encoding: vrhadd.s16 q0, q1, q2" {
    try expectEncoding(E.neonThreeSameQ, .{ .vrhadd_s, .i16, .q0, .q1, .q2 }, &.{0xf2120144});
}
test "arm32 encoding: vrhadd.u8 q14, q13, q12" {
    try expectEncoding(E.neonThreeSameQ, .{ .vrhadd_u, .i8, .q14, .q13, .q12 }, &.{0xf34ac1e8});
}
test "arm32 encoding: vcgt.s8 q0, q1, q2" {
    try expectEncoding(E.neonThreeSameQ, .{ .vcgt_s, .i8, .q0, .q1, .q2 }, &.{0xf2020344});
}
test "arm32 encoding: vcgt.u32 q8, q1, q9" {
    try expectEncoding(E.neonThreeSameQ, .{ .vcgt_u, .i32, .q8, .q1, .q9 }, &.{0xf3620362});
}
test "arm32 encoding: vcge.s16 q0, q1, q2" {
    try expectEncoding(E.neonThreeSameQ, .{ .vcge_s, .i16, .q0, .q1, .q2 }, &.{0xf2120354});
}
test "arm32 encoding: vcge.u8 q2, q3, q4" {
    try expectEncoding(E.neonThreeSameQ, .{ .vcge_u, .i8, .q2, .q3, .q4 }, &.{0xf3064358});
}
test "arm32 encoding: vshl.s32 q0, q1, q2" {
    try expectEncoding(E.neonThreeSameQ, .{ .vshl_s, .i32, .q0, .q2, .q1 }, &.{0xf2240442});
}
test "arm32 encoding: vshl.u64 q8, q9, q10" {
    try expectEncoding(E.neonThreeSameQ, .{ .vshl_u, .i64, .q8, .q10, .q9 }, &.{0xf37404e2});
}
test "arm32 encoding: vrshl.s8 q0, q1, q2" {
    try expectEncoding(E.neonThreeSameQ, .{ .vrshl_s, .i8, .q0, .q2, .q1 }, &.{0xf2040542});
}
test "arm32 encoding: vrshl.u16 q3, q4, q5" {
    try expectEncoding(E.neonThreeSameQ, .{ .vrshl_u, .i16, .q3, .q5, .q4 }, &.{0xf31a6548});
}
test "arm32 encoding: vmax.s8 q0, q1, q2" {
    try expectEncoding(E.neonThreeSameQ, .{ .vmax_s, .i8, .q0, .q1, .q2 }, &.{0xf2020644});
}
test "arm32 encoding: vmax.u32 q0, q1, q2" {
    try expectEncoding(E.neonThreeSameQ, .{ .vmax_u, .i32, .q0, .q1, .q2 }, &.{0xf3220644});
}
test "arm32 encoding: vmin.s16 q0, q1, q2" {
    try expectEncoding(E.neonThreeSameQ, .{ .vmin_s, .i16, .q0, .q1, .q2 }, &.{0xf2120654});
}
test "arm32 encoding: vmin.u8 q15, q14, q13" {
    try expectEncoding(E.neonThreeSameQ, .{ .vmin_u, .i8, .q15, .q14, .q13 }, &.{0xf34ce6fa});
}
test "arm32 encoding: vabd.s32 q0, q1, q2" {
    try expectEncoding(E.neonThreeSameQ, .{ .vabd_s, .i32, .q0, .q1, .q2 }, &.{0xf2220744});
}
test "arm32 encoding: vabd.u16 q0, q1, q2" {
    try expectEncoding(E.neonThreeSameQ, .{ .vabd_u, .i16, .q0, .q1, .q2 }, &.{0xf3120744});
}
test "arm32 encoding: vceq.i32 q0, q1, q2" {
    try expectEncoding(E.neonThreeSameQ, .{ .vceq, .i32, .q0, .q1, .q2 }, &.{0xf3220854});
}
test "arm32 encoding: vtst.8 q0, q1, q2" {
    try expectEncoding(E.neonThreeSameQ, .{ .vtst, .i8, .q0, .q1, .q2 }, &.{0xf2020854});
}
test "arm32 encoding: vmul.i16 q0, q1, q2" {
    try expectEncoding(E.neonThreeSameQ, .{ .vmul, .i16, .q0, .q1, .q2 }, &.{0xf2120954});
}
test "arm32 encoding: vmul.p8 q8, q9, q10" {
    try expectEncoding(E.neonThreeSameQ, .{ .vmul_p8, .i8, .q8, .q9, .q10 }, &.{0xf34209f4});
}
test "arm32 encoding: vqdmulh.s16 q0, q1, q2" {
    try expectEncoding(E.neonThreeSameQ, .{ .vqdmulh, .i16, .q0, .q1, .q2 }, &.{0xf2120b44});
}
test "arm32 encoding: vqrdmulh.s32 q0, q1, q2" {
    try expectEncoding(E.neonThreeSameQ, .{ .vqrdmulh, .i32, .q0, .q1, .q2 }, &.{0xf3220b44});
}
test "arm32 encoding: vqrdmulh.s16 q3, q4, q5" {
    try expectEncoding(E.neonThreeSameQ, .{ .vqrdmulh, .i16, .q3, .q4, .q5 }, &.{0xf3186b4a});
}
test "arm32 encoding: vadd.i32 d0, d1, d2" {
    try expectEncoding(E.neonThreeSameD, .{ .vadd, .i32, .d0, .d1, .d2 }, &.{0xf2210802});
}
test "arm32 encoding: vpadd.i8 d0, d1, d2" {
    try expectEncoding(E.neonThreeSameD, .{ .vpadd, .i8, .d0, .d1, .d2 }, &.{0xf2010b12});
}
test "arm32 encoding: vpadd.i32 d16, d17, d31" {
    try expectEncoding(E.neonThreeSameD, .{ .vpadd, .i32, .d16, .d17, .d31 }, &.{0xf2610bbf});
}
test "arm32 encoding: vpmax.s16 d0, d1, d2" {
    try expectEncoding(E.neonThreeSameD, .{ .vpmax_s, .i16, .d0, .d1, .d2 }, &.{0xf2110a02});
}
test "arm32 encoding: vpmax.u8 d0, d1, d2" {
    try expectEncoding(E.neonThreeSameD, .{ .vpmax_u, .i8, .d0, .d1, .d2 }, &.{0xf3010a02});
}
test "arm32 encoding: vpmin.s32 d0, d1, d2" {
    try expectEncoding(E.neonThreeSameD, .{ .vpmin_s, .i32, .d0, .d1, .d2 }, &.{0xf2210a12});
}
test "arm32 encoding: vpmin.u16 d0, d1, d2" {
    try expectEncoding(E.neonThreeSameD, .{ .vpmin_u, .i16, .d0, .d1, .d2 }, &.{0xf3110a12});
}
test "arm32 encoding: vand q0, q1, q2" {
    try expectEncoding(E.neonLogicQ, .{ .vand, .q0, .q1, .q2 }, &.{0xf2020154});
}
test "arm32 encoding: vbic q0, q1, q2" {
    try expectEncoding(E.neonLogicQ, .{ .vbic, .q0, .q1, .q2 }, &.{0xf2120154});
}
test "arm32 encoding: vorr q8, q9, q10" {
    try expectEncoding(E.neonLogicQ, .{ .vorr, .q8, .q9, .q10 }, &.{0xf26201f4});
}
test "arm32 encoding: vorr q1, q15, q15" {
    try expectEncoding(E.neonLogicQ, .{ .vorr, .q1, .q15, .q15 }, &.{0xf22e21fe});
}
test "arm32 encoding: vorn q0, q1, q2" {
    try expectEncoding(E.neonLogicQ, .{ .vorn, .q0, .q1, .q2 }, &.{0xf2320154});
}
test "arm32 encoding: veor q0, q1, q2" {
    try expectEncoding(E.neonLogicQ, .{ .veor, .q0, .q1, .q2 }, &.{0xf3020154});
}
test "arm32 encoding: vbsl q0, q1, q2" {
    try expectEncoding(E.neonLogicQ, .{ .vbsl, .q0, .q1, .q2 }, &.{0xf3120154});
}
test "arm32 encoding: vbit q0, q1, q2" {
    try expectEncoding(E.neonLogicQ, .{ .vbit, .q0, .q1, .q2 }, &.{0xf3220154});
}
test "arm32 encoding: vbif q0, q1, q2" {
    try expectEncoding(E.neonLogicQ, .{ .vbif, .q0, .q1, .q2 }, &.{0xf3320154});
}
test "arm32 encoding: veor d16, d17, d18" {
    try expectEncoding(E.neonLogicD, .{ .veor, .d16, .d17, .d18 }, &.{0xf34101b2});
}
test "arm32 encoding: vaddl.s8 q0, d1, d2" {
    try expectEncoding(E.neonThreeDiff, .{ .vaddl_s, .i8, .q0, .d1, .d2 }, &.{0xf2810002});
}
test "arm32 encoding: vaddl.u16 q0, d1, d2" {
    try expectEncoding(E.neonThreeDiff, .{ .vaddl_u, .i16, .q0, .d1, .d2 }, &.{0xf3910002});
}
test "arm32 encoding: vsubl.s32 q0, d1, d2" {
    try expectEncoding(E.neonThreeDiff, .{ .vsubl_s, .i32, .q0, .d1, .d2 }, &.{0xf2a10202});
}
test "arm32 encoding: vsubl.u8 q0, d1, d2" {
    try expectEncoding(E.neonThreeDiff, .{ .vsubl_u, .i8, .q0, .d1, .d2 }, &.{0xf3810202});
}
test "arm32 encoding: vabal.s16 q0, d1, d2" {
    try expectEncoding(E.neonThreeDiff, .{ .vabal_s, .i16, .q0, .d1, .d2 }, &.{0xf2910502});
}
test "arm32 encoding: vabal.u8 q0, d1, d2" {
    try expectEncoding(E.neonThreeDiff, .{ .vabal_u, .i8, .q0, .d1, .d2 }, &.{0xf3810502});
}
test "arm32 encoding: vabdl.s8 q0, d1, d2" {
    try expectEncoding(E.neonThreeDiff, .{ .vabdl_s, .i8, .q0, .d1, .d2 }, &.{0xf2810702});
}
test "arm32 encoding: vabdl.u16 q0, d1, d2" {
    try expectEncoding(E.neonThreeDiff, .{ .vabdl_u, .i16, .q0, .d1, .d2 }, &.{0xf3910702});
}
test "arm32 encoding: vmlal.s32 q0, d1, d2" {
    try expectEncoding(E.neonThreeDiff, .{ .vmlal_s, .i32, .q0, .d1, .d2 }, &.{0xf2a10802});
}
test "arm32 encoding: vmlal.u32 q8, d17, d18" {
    try expectEncoding(E.neonThreeDiff, .{ .vmlal_u, .i32, .q8, .d17, .d18 }, &.{0xf3e108a2});
}
test "arm32 encoding: vmull.s16 q0, d1, d2" {
    try expectEncoding(E.neonThreeDiff, .{ .vmull_s, .i16, .q0, .d1, .d2 }, &.{0xf2910c02});
}
test "arm32 encoding: vmull.u32 q15, d30, d31" {
    try expectEncoding(E.neonThreeDiff, .{ .vmull_u, .i32, .q15, .d30, .d31 }, &.{0xf3eeecaf});
}
test "arm32 encoding: vmull.p8 q8, d17, d31" {
    try expectEncoding(E.neonThreeDiff, .{ .vmull_p8, .i8, .q8, .d17, .d31 }, &.{0xf2c10eaf});
}
test "arm32 encoding: vrev64.8 q0, q1" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vrev64, .i8, .q0, .q1 }, &.{0xf3b00042});
}
test "arm32 encoding: vrev32.16 q0, q1" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vrev32, .i16, .q0, .q1 }, &.{0xf3b400c2});
}
test "arm32 encoding: vrev16.8 q0, q1" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vrev16, .i8, .q0, .q1 }, &.{0xf3b00142});
}
test "arm32 encoding: vpaddl.s8 q0, q1" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vpaddl_s, .i8, .q0, .q1 }, &.{0xf3b00242});
}
test "arm32 encoding: vpaddl.u32 q8, q9" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vpaddl_u, .i32, .q8, .q9 }, &.{0xf3f802e2});
}
test "arm32 encoding: vcls.s16 q0, q1" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vcls, .i16, .q0, .q1 }, &.{0xf3b40442});
}
test "arm32 encoding: vclz.i32 q0, q1" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vclz, .i32, .q0, .q1 }, &.{0xf3b804c2});
}
test "arm32 encoding: vcnt.8 q0, q1" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vcnt, .i8, .q0, .q1 }, &.{0xf3b00542});
}
test "arm32 encoding: vmvn q0, q1" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vmvn, .i8, .q0, .q1 }, &.{0xf3b005c2});
}
test "arm32 encoding: vpadal.s16 q0, q1" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vpadal_s, .i16, .q0, .q1 }, &.{0xf3b40642});
}
test "arm32 encoding: vpadal.u8 q0, q1" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vpadal_u, .i8, .q0, .q1 }, &.{0xf3b006c2});
}
test "arm32 encoding: vqabs.s8 q0, q1" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vqabs, .i8, .q0, .q1 }, &.{0xf3b00742});
}
test "arm32 encoding: vqneg.s32 q0, q1" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vqneg, .i32, .q0, .q1 }, &.{0xf3b807c2});
}
test "arm32 encoding: vcgt.s8 q0, q1, #0" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vcgt_zero, .i8, .q0, .q1 }, &.{0xf3b10042});
}
test "arm32 encoding: vcge.s16 q0, q1, #0" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vcge_zero, .i16, .q0, .q1 }, &.{0xf3b500c2});
}
test "arm32 encoding: vceq.i32 q0, q1, #0" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vceq_zero, .i32, .q0, .q1 }, &.{0xf3b90142});
}
test "arm32 encoding: vcle.s8 q0, q1, #0" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vcle_zero, .i8, .q0, .q1 }, &.{0xf3b101c2});
}
test "arm32 encoding: vclt.s16 q0, q1, #0" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vclt_zero, .i16, .q0, .q1 }, &.{0xf3b50242});
}
test "arm32 encoding: vabs.s8 q0, q1" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vabs, .i8, .q0, .q1 }, &.{0xf3b10342});
}
test "arm32 encoding: vneg.s32 q10, q11" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vneg, .i32, .q10, .q11 }, &.{0xf3f943e6});
}
test "arm32 encoding: vswp q0, q1" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vswp, .i8, .q0, .q1 }, &.{0xf3b20042});
}
test "arm32 encoding: vtrn.8 q0, q1" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vtrn, .i8, .q0, .q1 }, &.{0xf3b200c2});
}
test "arm32 encoding: vuzp.16 q0, q1" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vuzp, .i16, .q0, .q1 }, &.{0xf3b60142});
}
test "arm32 encoding: vzip.32 q8, q9" {
    try expectEncoding(E.neonTwoMiscQ, .{ .vzip, .i32, .q8, .q9 }, &.{0xf3fa01e2});
}
test "arm32 encoding: vrev64.32 d0, d1" {
    try expectEncoding(E.neonTwoMiscD, .{ .vrev64, .i32, .d0, .d1 }, &.{0xf3b80001});
}
test "arm32 encoding: vzip.8 d16, d17" {
    try expectEncoding(E.neonTwoMiscD, .{ .vzip, .i8, .d16, .d17 }, &.{0xf3f201a1});
}
test "arm32 encoding: vcnt.8 d30, d31" {
    try expectEncoding(E.neonTwoMiscD, .{ .vcnt, .i8, .d30, .d31 }, &.{0xf3f0e52f});
}
test "arm32 encoding: vmovn.i16 d0, q1" {
    try expectEncoding(E.neonNarrow, .{ .vmovn, .i8, .d0, .q1 }, &.{0xf3b20202});
}
test "arm32 encoding: vmovn.i64 d17, q9" {
    try expectEncoding(E.neonNarrow, .{ .vmovn, .i32, .d17, .q9 }, &.{0xf3fa1222});
}
test "arm32 encoding: vqmovun.s32 d1, q2" {
    try expectEncoding(E.neonNarrow, .{ .vqmovun, .i16, .d1, .q2 }, &.{0xf3b61244});
}
test "arm32 encoding: vqmovn.s64 d2, q3" {
    try expectEncoding(E.neonNarrow, .{ .vqmovn_s, .i32, .d2, .q3 }, &.{0xf3ba2286});
}
test "arm32 encoding: vqmovn.u16 d16, q9" {
    try expectEncoding(E.neonNarrow, .{ .vqmovn_u, .i8, .d16, .q9 }, &.{0xf3f202e2});
}
test "arm32 encoding: vshr.s8 q0, q1, #1" {
    try expectEncoding(E.neonShiftRightQ, .{ .vshr_s, .i8, .q0, .q1, 1 }, &.{0xf28f0052});
}
test "arm32 encoding: vshr.u16 q0, q1, #16" {
    try expectEncoding(E.neonShiftRightQ, .{ .vshr_u, .i16, .q0, .q1, 16 }, &.{0xf3900052});
}
test "arm32 encoding: vshr.s64 q8, q9, #63" {
    try expectEncoding(E.neonShiftRightQ, .{ .vshr_s, .i64, .q8, .q9, 63 }, &.{0xf2c100f2});
}
test "arm32 encoding: vsra.s32 q0, q1, #5" {
    try expectEncoding(E.neonShiftRightQ, .{ .vsra_s, .i32, .q0, .q1, 5 }, &.{0xf2bb0152});
}
test "arm32 encoding: vsra.u64 q0, q1, #64" {
    try expectEncoding(E.neonShiftRightQ, .{ .vsra_u, .i64, .q0, .q1, 64 }, &.{0xf38001d2});
}
test "arm32 encoding: vrshr.s64 q0, q1, #1" {
    try expectEncoding(E.neonShiftRightQ, .{ .vrshr_s, .i64, .q0, .q1, 1 }, &.{0xf2bf02d2});
}
test "arm32 encoding: vrshr.u8 q0, q1, #8" {
    try expectEncoding(E.neonShiftRightQ, .{ .vrshr_u, .i8, .q0, .q1, 8 }, &.{0xf3880252});
}
test "arm32 encoding: vrsra.s16 q0, q1, #3" {
    try expectEncoding(E.neonShiftRightQ, .{ .vrsra_s, .i16, .q0, .q1, 3 }, &.{0xf29d0352});
}
test "arm32 encoding: vrsra.u32 q0, q1, #32" {
    try expectEncoding(E.neonShiftRightQ, .{ .vrsra_u, .i32, .q0, .q1, 32 }, &.{0xf3a00352});
}
test "arm32 encoding: vshl.i8 q0, q1, #0" {
    try expectEncoding(E.neonShiftLeftQ, .{ .i8, .q0, .q1, 0 }, &.{0xf2880552});
}
test "arm32 encoding: vshl.i16 q0, q1, #15" {
    try expectEncoding(E.neonShiftLeftQ, .{ .i16, .q0, .q1, 15 }, &.{0xf29f0552});
}
test "arm32 encoding: vshl.i32 q0, q1, #31" {
    try expectEncoding(E.neonShiftLeftQ, .{ .i32, .q0, .q1, 31 }, &.{0xf2bf0552});
}
test "arm32 encoding: vshl.i64 q8, q9, #63" {
    try expectEncoding(E.neonShiftLeftQ, .{ .i64, .q8, .q9, 63 }, &.{0xf2ff05f2});
}
test "arm32 encoding: vshrn.i16 d0, q1, #8" {
    try expectEncoding(E.neonShiftNarrow, .{ .vshrn, .i8, .d0, .q1, 8 }, &.{0xf2880812});
}
test "arm32 encoding: vrshrn.i32 d1, q2, #1" {
    try expectEncoding(E.neonShiftNarrow, .{ .vrshrn, .i16, .d1, .q2, 1 }, &.{0xf29f1854});
}
test "arm32 encoding: vqshrun.s64 d2, q3, #32" {
    try expectEncoding(E.neonShiftNarrow, .{ .vqshrun, .i32, .d2, .q3, 32 }, &.{0xf3a02816});
}
test "arm32 encoding: vqrshrun.s16 d3, q4, #4" {
    try expectEncoding(E.neonShiftNarrow, .{ .vqrshrun, .i8, .d3, .q4, 4 }, &.{0xf38c3858});
}
test "arm32 encoding: vqshrn.s32 d0, q1, #16" {
    try expectEncoding(E.neonShiftNarrow, .{ .vqshrn_s, .i16, .d0, .q1, 16 }, &.{0xf2900912});
}
test "arm32 encoding: vqshrn.u64 d0, q1, #1" {
    try expectEncoding(E.neonShiftNarrow, .{ .vqshrn_u, .i32, .d0, .q1, 1 }, &.{0xf3bf0912});
}
test "arm32 encoding: vqrshrn.s16 d0, q1, #8" {
    try expectEncoding(E.neonShiftNarrow, .{ .vqrshrn_s, .i8, .d0, .q1, 8 }, &.{0xf2880952});
}
test "arm32 encoding: vqrshrn.u32 d16, q9, #2" {
    try expectEncoding(E.neonShiftNarrow, .{ .vqrshrn_u, .i16, .d16, .q9, 2 }, &.{0xf3de0972});
}
test "arm32 encoding: vmovl.s8 q0, d1" {
    try expectEncoding(E.neonShiftLeftLong, .{ .signed, .i8, .q0, .d1, 0 }, &.{0xf2880a11});
}
test "arm32 encoding: vmovl.u16 q1, d2" {
    try expectEncoding(E.neonShiftLeftLong, .{ .unsigned, .i16, .q1, .d2, 0 }, &.{0xf3902a12});
}
test "arm32 encoding: vmovl.u32 q8, d31" {
    try expectEncoding(E.neonShiftLeftLong, .{ .unsigned, .i32, .q8, .d31, 0 }, &.{0xf3e00a3f});
}
test "arm32 encoding: vshll.s32 q8, d17, #31" {
    try expectEncoding(E.neonShiftLeftLong, .{ .signed, .i32, .q8, .d17, 31 }, &.{0xf2ff0a31});
}
test "arm32 encoding: vshll.u8 q2, d3, #7" {
    try expectEncoding(E.neonShiftLeftLong, .{ .unsigned, .i8, .q2, .d3, 7 }, &.{0xf38f4a13});
}
test "arm32 encoding: vmov.i8 q0, #0xff" {
    try expectEncoding(E.vmovI8Q, .{ .q0, 0xff }, &.{0xf3870e5f});
}
test "arm32 encoding: vmov.i8 q9, #0x0" {
    try expectEncoding(E.vmovI8Q, .{ .q9, 0x00 }, &.{0xf2c02e50});
}
test "arm32 encoding: vmov.i8 q1, #0x81" {
    try expectEncoding(E.vmovI8Q, .{ .q1, 0x81 }, &.{0xf3802e51});
}
test "arm32 encoding: vmov.i64 q0, #0xff00ff00ff00ff00" {
    try expectEncoding(E.vmovI64Q, .{ .q0, 0xaa }, &.{0xf3820e7a});
}
test "arm32 encoding: vmov.i64 q15, #0xffffffffffffffff" {
    try expectEncoding(E.vmovI64Q, .{ .q15, 0xff }, &.{0xf3c7ee7f});
}
test "arm32 encoding: vext.8 q0, q1, q2, #8" {
    try expectEncoding(E.vextQ, .{ .q0, .q1, .q2, 8 }, &.{0xf2b20844});
}
test "arm32 encoding: vext.8 q8, q9, q15, #15" {
    try expectEncoding(E.vextQ, .{ .q8, .q9, .q15, 15 }, &.{0xf2f20fee});
}
test "arm32 encoding: vtbl.8 d0, {d2, d3}, d4" {
    try expectEncoding(E.vtbl, .{ .d0, .d2, 2, .d4 }, &.{0xf3b20904});
}
test "arm32 encoding: vtbl.8 d16, {d17}, d18" {
    try expectEncoding(E.vtbl, .{ .d16, .d17, 1, .d18 }, &.{0xf3f108a2});
}
test "arm32 encoding: vtbl.8 d1, {d28, d29, d30, d31}, d0" {
    try expectEncoding(E.vtbl, .{ .d1, .d28, 4, .d0 }, &.{0xf3bc1b80});
}
test "arm32 encoding: vdup.8 q0, r1" {
    try expectEncoding(E.vdupQFromCore, .{ .i8, .q0, .r1 }, &.{0xeee01b10});
}
test "arm32 encoding: vdup.16 q9, r12" {
    try expectEncoding(E.vdupQFromCore, .{ .i16, .q9, .r12 }, &.{0xeea2cbb0});
}
test "arm32 encoding: vdup.32 q15, r0" {
    try expectEncoding(E.vdupQFromCore, .{ .i32, .q15, .r0 }, &.{0xeeae0b90});
}
test "arm32 encoding: vdup.8 q0, d1[7]" {
    try expectEncoding(E.vdupQFromLane, .{ .i8, .q0, .d1, 7 }, &.{0xf3bf0c41});
}
test "arm32 encoding: vdup.16 q1, d17[3]" {
    try expectEncoding(E.vdupQFromLane, .{ .i16, .q1, .d17, 3 }, &.{0xf3be2c61});
}
test "arm32 encoding: vdup.32 q8, d31[1]" {
    try expectEncoding(E.vdupQFromLane, .{ .i32, .q8, .d31, 1 }, &.{0xf3fc0c6f});
}
test "arm32 encoding: vmov.8 d0[7], r1" {
    try expectEncoding(E.vmovLaneFromCore, .{ .i8, .d0, 7, .r1 }, &.{0xee601b70});
}
test "arm32 encoding: vmov.8 d1[2], r0" {
    try expectEncoding(E.vmovLaneFromCore, .{ .i8, .d1, 2, .r0 }, &.{0xee410b50});
}
test "arm32 encoding: vmov.16 d17[2], r2" {
    try expectEncoding(E.vmovLaneFromCore, .{ .i16, .d17, 2, .r2 }, &.{0xee212bb0});
}
test "arm32 encoding: vmov.32 d31[1], r12" {
    try expectEncoding(E.vmovLaneFromCore, .{ .i32, .d31, 1, .r12 }, &.{0xee2fcb90});
}
test "arm32 encoding: vmov.u8 r0, d1[5]" {
    try expectEncoding(E.vmovCoreFromLane, .{ .unsigned, .i8, .r0, .d1, 5 }, &.{0xeef10b30});
}
test "arm32 encoding: vmov.s8 r1, d2[0]" {
    try expectEncoding(E.vmovCoreFromLane, .{ .signed, .i8, .r1, .d2, 0 }, &.{0xee521b10});
}
test "arm32 encoding: vmov.u16 r2, d16[3]" {
    try expectEncoding(E.vmovCoreFromLane, .{ .unsigned, .i16, .r2, .d16, 3 }, &.{0xeeb02bf0});
}
test "arm32 encoding: vmov.s16 r3, d17[1]" {
    try expectEncoding(E.vmovCoreFromLane, .{ .signed, .i16, .r3, .d17, 1 }, &.{0xee113bf0});
}
test "arm32 encoding: vmov.32 r4, d31[1]" {
    try expectEncoding(E.vmovCoreFromLane, .{ .unsigned, .i32, .r4, .d31, 1 }, &.{0xee3f4b90});
}
test "arm32 encoding: vld1.8 {d0, d1}, [r0]" {
    try expectEncoding(E.vld1Q, .{ .q0, .r0 }, &.{0xf4200a0f});
}
test "arm32 encoding: vld1.8 {d16, d17}, [sp]" {
    try expectEncoding(E.vld1Q, .{ .q8, .r13 }, &.{0xf46d0a0f});
}
test "arm32 encoding: vst1.8 {d2, d3}, [r11]" {
    try expectEncoding(E.vst1Q, .{ .q1, .r11 }, &.{0xf40b2a0f});
}
